clinica/pipelines/pet_volume/pet_volume_pipeline.py
Add correct reading and interpretation of the PSF information for the PET Volume pipeline.
=> Bugfix pvc

clinica/iotools/bids_utils.py, clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py, clinica/pipelines/machine_learning/input.py
Will avoid to find 1 - accuracy when computing the metrics on a test set.
=> Sort diagnosis list in ML datasets

clinica/cmdline.py, test/nonregression/test_run_pipelines.py, test/nonregression/testing_tools.py
T1-FreeSurfer-Longitudinal pipeline is currently removed from Clinica for the upcoming release.
=> Comment T1-FreeSurfer-Longitudinal pipeline (CI & CLI)

clinica/iotools/utils/data_handling.py, clinica/iotools/utils/data_handling_cli.py, clinica/pipelines/t1_volume_existing_template/t1_volume_existing_template_pipeline.py, clinica/pipelines/t1_volume_new_template/t1_volume_new_template_pipeline.py, clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py, clinica/utils/io.py, test/nonregression/test_run_iotools.py
This PR aims to mitigate drawbacks of precendently merged center_nifti tool. 
We want to center the niftis of only specified modality in argument.
```
Optional arguments:
--modality MODALITY, -m MODALITY
List of modalities you want to center the NIfTI images
(ex: "t1w fdg_pet dwi"). Default="t1w"
```
All the niftis that contains one of the keyword in their filename will be kept.
Wiki has been updated: https://github.com/aramis-lab/clinica/wiki/IO
A series of experiment have been conducted: we take a volume whose center is on the origin of the world coordinate system. We add an offset using coordinates of affine matrix [0, 3], [1, 3], [2, 3] (or by modifying the header['srow_x'][3], header['srow_y'][3], header['srow_z'][3], this is strictly equivalent).
It has been determined that volumes …
=> Improve center nifti

clinica/pipelines/machine_learning_spatial_svm/spatial_svm_utils.py, environment.yml, test/nonregression/testing_tools.py
This PR changes the way how NaN values are found when loading an image.
=> Change how to find NaN values in images

clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py, clinica/resources/templates/pipeline_template/README.md.j2, clinica/resources/templates/pipeline_template/cli.py.j2, clinica/resources/templates/pipeline_template/pipeline.py.j2, clinica/resources/templates/pipeline_template/utils.py.j2
When reviewing PR #62, I noticed a few mistakes in the generated template. I fixed this and took the oppportunity to update/harmonize it regarding the last modifications of Clinica.
=> Improve Jinja2 template

clinica/pipelines/statistics_volume_correction/statistics_volume_correction_pipeline.py, clinica/pipelines/t1_linear/t1_linear_cli.py
Fix for _StatisticsVolumeCorrection_ pipeline and add CLI description for _T1Linear_
=> Add fetch automatically template for StatisticsVolumeCorrection pipeline if it doesn't exist

clinica/pipelines/statistics_volume_correction/statistics_volume_correction_pipeline.py, clinica/pipelines/t1_linear/t1_linear_pipeline.py, clinica/utils/input_files.py, clinica/utils/inputs.py
Update the `fetch_file` function, verify downloaded file with SHA256.
=> Update fetch_file function

clinica/pipelines/t1_linear/t1_linear_utils.py, environment.yml, requirements.txt
Add parameter to nilearn function, in T1_linear pipeline, in order to use the last release o this library. It updates also requirements.
=> Update T1_linear pipeline

Jenkinsfile
This PR includes two main changes:
* Automatically generation of testing reports in order to be displayed in the CI interface
* Jenkinsfile modification. It allows to recreate the Python environment  if the requirement file  changes.
=> CI modifications

clinica/utils/ux.py
Should resolve https://github.com/aramis-lab/AD-DL/issues/79.
=> Remove non-breaking spaces

.github/workflows/codeql-analysis.yml
This PR adds code scanning for Clinica since ARAMIS Lab has access to this beta test.
=> Enabling GitHub code scanning for Clinica

clinica/utils/check_dependency.py
=> Fix check_petpvc function

clinica/iotools/bids_utils.py, clinica/iotools/converter_utils.py, clinica/iotools/converters/adni_to_bids/adni_modalities/adni_av45_fbb_pet.py, clinica/iotools/converters/adni_to_bids/adni_modalities/adni_dwi.py, clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fdg_pet.py, clinica/iotools/converters/adni_to_bids/adni_modalities/adni_flair.py, clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fmri.py, clinica/iotools/converters/adni_to_bids/adni_modalities/adni_pib_pet.py, clinica/iotools/converters/adni_to_bids/adni_modalities/adni_t1.py, clinica/iotools/converters/adni_to_bids/adni_modalities/adni_tau_pet.py, clinica/iotools/converters/adni_to_bids/adni_to_bids.py, clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py, clinica/iotools/converters/adni_to_bids/adni_utils.py, clinica/iotools/converters/aibl_to_bids/aibl_to_bids_cli.py, clinica/iotools/converters/aibl_to_bids/aibl_utils.py, clinica/iotools/converters/nifd_to_bids/nifd_to_bids.py, clinica/iotools/converters/nifd_to_bids/nifd_to_bids_cli.py, clinica/iotools/converters/nifd_to_bids/nifd_utils.py, clinica/iotools/converters/nifd_to_bids/preprocessing/parse_ida.py, clinica/iotools/converters/nifd_to_bids/preprocessing/update_clinical_info.py, clinica/iotools/converters/nifd_to_bids/utils/conv_image_folders.py, clinica/iotools/converters/nifd_to_bids/utils/descriptor.py, clinica/iotools/converters/nifd_to_bids/utils/manage_conflicts.py, clinica/iotools/converters/nifd_to_bids/utils/parse_clinical.py, clinica/iotools/converters/nifd_to_bids/utils/patient.py, clinica/iotools/converters/oasis_to_bids/oasis_to_bids_cli.py, clinica/iotools/utils/data_handling.py, clinica/iotools/utils/pipeline_handling.py, clinica/utils/check_dependency.py
Hi,
This PR is mainly for cleaning regarding converters:
- Harmonize docstring (Google Style, ' replacement, header removal)
- Add check_dcm2nii(x) functions
- Harmonize how dependencies are checked for converters
=> Harmonize docstring and how dependancies are checked for converters

clinica/cmdline.py, clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_longitudinal_correction_pipeline.py, clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_longitudinal_correction_utils.py, test/instantiation/test_instantiate_all_pipelines.py, test/nonregression/test_run_pipelines.py
Resolves #121
Normally, the CI should pass 🤞
=> Add T1-FreeSurfer-Longitudinal pipeline

clinica/iotools/converters/nifd_to_bids/nifd_to_bids.py
=> Use DataDictionary_NIFD_*.xlsx on server if file is missing

.jenkins/scripts/publish.sh, Jenkinsfile, docs/requirements.txt
This PR is intended to:
- Create an environment in CI machines
- Build the doc using mkdocs
- Publish the doc
Once verification, link in official web site can be redirected to new location.
Docs for `dev` branch here : https://aramislab.paris.inria.fr/clinica/docs/public/
Docs for each PR here : https://aramislab.paris.inria.fr/clinica/docs/public/branches/{branch_name}
=> Build and publish documentation with CI

docs/Pipelines/T1_Linear.md
Add tip in documentation for T1-Linear to emphasize that `clinica run t1-linear --help` will display all the possible options for this pipeline.
=> Update t1-linear doc

clinica/iotools/converters/adni_to_bids/adni_to_bids.py, clinica/iotools/converters/adni_to_bids/adni_utils.py
There were some changes on the diagnosis at screening for ADNI3 participants.
See https://groups.google.com/g/adni-data/c/whYhKafN_0Q for more information.
I am waiting for an answer before merging this PR.
=> Add diagnosis at screening missing for some ADNI3 participants

clinica/iotools/utils/pipeline_handling.py
Hi @mdiazmel ,
The user I sent data to told me that the suffix by used was a bit misleading. This PR intends to change it.
=> Change suffix

clinica/cmdline.py
Add `--version` or `-V` argument to command line.
=> Add '--version' argument to command line

clinica/iotools/utils/data_handling_cli.py, clinica/pipelines/statistics_surface/statistics_surface_utils.py, clinica/pipelines/t1_freesurfer/t1_freesurfer_utils.py, clinica/pipelines/t1_freesurfer_longitudinal/longitudinal_utils.py, clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_longitudinal_correction_utils.py, clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_template_utils.py, clinica/utils/filemanip.py, clinica/utils/freesurfer.py
Hi,
This PR continues the previous work to simplify the creation of folder with recent `makedirs(folder, exist_ok=True)` function.
Alex
=> Use makedirs(folder, exist_ok=True) function

clinica/cmdline.py, clinica/pipelines/pet_surface/pet_surface_utils.py, docs/CAPS/Specifications.md, docs/Pipelines/PET_Surface_Longitudinal.md, docs/index.md, mkdocs.yml
- Add `pet-surface-longitudinal` to list of pipeline
- Add ``pet-surface-longitudinal` Wiki & CAPS page 
- Hide FreeSurfer output messages when running `pet-surface` / `pet-surface-longitudinal` pipelines
=> Add pet-surface-longitudinal

mkdocs.yml
Add version popup to mkdocs (add js script)
=> Add version popup menu to documentation

test/nonregression/pipelines/test_run_pipelines_pet.py
Change nonregression test for PETLinear to keep coherence with other tests.
=> Edit nonregression test for PETLinear

clinica/iotools/utils/data_handling.py
Fix problem with duplicate rows due to duplicated code
=> Remove redundant code in create_merge_file

clinica/iotools/utils/data_handling_cli.py, test/nonregression/iotools/test_run_utils.py
=> Fix CLI for merge-tsv iotool

clinica/pipelines/pet_surface/info.json
=> Add spm12 depdency check for pet_surface

clinica/iotools/converters/aibl_to_bids/aibl_utils.py, docs/Converters/AIBL2BIDS.md
PET files are AIBL are not centered, which causes problems when running `pet-surface`.
=> Center output nifti files of AIBL

clinica/engine/cmdparser.py, clinica/iotools/utils/data_handling.py, clinica/pipelines/t1_freesurfer/t1_freesurfer_cli.py, clinica/pipelines/t1_freesurfer/t1_freesurfer_pipeline.py, test/instantiation/test_instantiate_all_pipelines.py, test/nonregression/pipelines/test_run_pipelines_anat.py
Closes #207 .
Could not test yet as the cluster is down.
=> Add option to skip Clinica question

.github/workflows/cleanEnvsJenkins.yml
=> Fix arguments in GH action to clean conda envs in CI agents

.github/workflows/cleanEnvsJenkins.yml
Fix how to read token into the workflow for GH actions
=> Add token as an env variable

docs/Converters/ADNI2BIDS.md
* Update the doc with the new processing order for t1w images in adni-to-bids. 
* Add warning about imageID in resulting t1_paths.csv BIDS file
=> Doc adni to bids update

.github/workflows/cleanEnvsJenkins.yml
=> Fix env variable name

docs/InteractingWithClinica.md
Another modest contribution to our docs
=> Update URL for list of BIDS converters

clinica/pipelines/t1_linear/t1_linear_pipeline.py
This PR intends to fix a minor bug encountered because of cprint in `t1-linear`.
=> Fix error message

requirements.txt
We depend on it in the pipeline engine code
=> Add networkx to dependencies

clinica/iotools/converter_utils.py, docs/IO.md, mkdocs.yml
=> Doc check-missing-processing

clinica/pipelines/statistics_volume_correction/statistics_volume_correction_cli.py
Looks like a copy-pasting accident.
=> Fix parameters of s-v-c pipeline

clinica/iotools/utils/data_handling.py
In this exception handling part of the function where the import is missing.
=> Add missing import of cprint

clinica/iotools/utils/cli.py, clinica/iotools/utils/data_handling.py, clinica/pipelines/engine.py
=> Handle input prompts with Click

clinica/iotools/utils/data_handling.py, clinica/iotools/utils/pipeline_handling.py
The new CLI defaults modified some command line option default values. Relevant code needed changing to prevent errors.
=> Modify logical checks to adapt with new default dtypes

clinica/cmdline.py, clinica/iotools/converters/adni_to_bids/adni_utils.py
Fix a bug in ADNI converter that prevented the calculation of the correct age in the session files.
=> Apply session filter to the correct column in ADNIMERGE

clinica/pipelines/t1_volume/t1_volume_cli.py
See: https://click.palletsprojects.com/en/8.0.x/advanced/?highlight=context#invoking-other-commands
Closes #320
=> Fix command forwarding in t1-volume pipeline

clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_longitudinal_cli.py
See: https://click.palletsprojects.com/en/8.0.x/advanced/?highlight=context#invoking-other-commands
Solves the same problem as #321 for another pipeline.
=> Fix command forwarding in t1-freesurfer_longitudinal pipeline

clinica/cmdline.py
=> Use Clinica's logging verbosity for nipype

clinica/iotools/converters/adni_to_bids/adni_utils.py, clinica/pipelines/t1_freesurfer/t1_freesurfer_pipeline.py, clinica/pipelines/t1_linear/t1_linear_pipeline.py, clinica/utils/inputs.py
On ADNI, add the column tau_stat (tau status) and a_stat (amyloid status) to the sessions.tsv, computed with the adni_ptau for the tau_stat, and computed with adni_av45, adni_pib and adni_abeta for the a_stat.
=> Enh tau amyloid status session tsv

clinica/iotools/converters/adni_to_bids/adni_utils.py
Fix the filter_subj_bids function, which did not apply the changes to the dataframe and caused the converters to crash.
=> Fix the filter_subj_bids function

clinica/iotools/bids_utils.py, clinica/iotools/converters/oasis3_to_bids/oasis3_to_bids.py, clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py
Change hard-coded lines that makes the converter crash to dynamic.
Solves issue #331
=> Change the subj_dir from hard coded to dynamic in bids_utils

docs/InteractingWithClinica.md
Change arguments typography and add `Common options` subsection to "Interacting with Clinica"
=> Edit 'Interacting with Clinica' section to be coherent with recent changes in CLI

clinica/iotools/converters/cli_param.py, clinica/pipelines/cli_param/argument.py, clinica/pipelines/cli_param/option.py
- Restrict path parameters to one of file or directory
- Do not force path checks on output folders
Closes #364
=> Improve contraints on path parameters

clinica/cmdline.py, setup.py
=> Do not display the traceback of Clinica exceptions

clinica/utils/check_dependency.py, docs/Third-party.md
=> Drop check for MRTRIX_HOME envvar

clinica/pipelines/deeplearning_prepare_data/deeplearning_prepare_data_pipeline.py, test/nonregression/pipelines/test_run_pipelines_dl.py
Fix default parameters for deeplearning prepare data and the non regression tests.
=> Fix default parameters for nonregression tests dlpd

clinica/pipelines/t1_volume_create_dartel/t1_volume_create_dartel_pipeline.py, clinica/pipelines/t1_volume_dartel2mni/t1_volume_dartel2mni_pipeline.py, clinica/pipelines/t1_volume_register_dartel/t1_volume_register_dartel_pipeline.py, clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py
Finish harmonization of `check_pipeline_parameters` method in all pipelines.
=> Use Python dict setdefault()

clinica/iotools/converters/adni_to_bids/adni_utils.py
=> Fix ValueError in adni utils

clinica/pipelines/deeplearning_prepare_data/deeplearning_prepare_data_utils.py, clinica/pipelines/machine_learning/input.py, clinica/pipelines/machine_learning_spatial_svm/spatial_svm_utils.py, clinica/utils/mri_registration.py
As a follow-up for #373 where a few edge-cases were found afterwards.
=> Fix selected default value handling

clinica/pipelines/dwi_connectome/dwi_connectome_pipeline.py, clinica/pipelines/dwi_connectome/dwi_connectome_utils.py
Also used f-string formatting as well as calls to some function in `utils/*.py`.
=> Apply black formatting to DWI-Connectome

clinica/resources/atlases/atlas-AAL2_dseg.tsv
=> Fix ROI index for left amygdala in AAL2 atlas

docs/Pipelines/DWI_Connectome.md
See https://groups.google.com/g/clinica-user/c/-nvQfDSzGRE/m/PTGYG-YRBAAJ for full discussion about it.
=> Fix DWI-Connectome description paragraph

.jenkins/scripts/find_env.sh
Fix Conda initialization in CI scripts.
=> Fix bash instruction to init conda

clinica/iotools/converters/adni_to_bids/adni_utils.py, clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py
Corrects two issues with adni2bids converter:
-Update diagnosis field entries from Dementia to AD 
-Remove rows with Empty or "Nv" value for the sessions
=> Update fields in ADNI sessions file

clinica/iotools/converters/nifd_to_bids/nifd_utils.py
For both the flat and nested NIFD layouts, the image data ID is encoded in the filenames. This PR updates the image data finder to parse these IDs from the files before computing the image data ID to source directory mapping.
Closes #406
=> Fix imaging data finder for alternative NIFD layout

CITATION.cff
About citation files integration on GitHub: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
Check the `Cite this repository` section on the right handside of the GitHub interface for this branch.
Closes #350
=> Add minimal citation file

clinica/iotools/bids_utils.py, clinica/iotools/utils/data_handling.py, test/nonregression/iotools/test_run_converters.py
Correct the assignment of sess list in OASIS converter
=> Add get_bids_sess_list function

test/nonregression/iotools/test_run_converters.py
Change the function call for oasis3tobids since the converter was remodelled.
=> Fix oasis3 non regression ci test

clinica/utils/atlas.py
Add new checksum to list of allowed checksums for fsl atlas
=> Add new sha256 checksum for JHU-ICBM-labels-1mm atlas

Jenkinsfile
=> CI: Autocleanup of build environments

clinica/pipelines/cli_param/argument.py, clinica/pipelines/statistics_volume/statistics_volume_cli.py, clinica/pipelines/statistics_volume/statistics_volume_pipeline.py, test/instantiation/test_instantiate_all_pipelines.py
=> Fix orig_input_data argument in StatisticsVolume

test/nonregression/pipelines/test_run_pipelines_stats.py
Fix parameter name for StatisticsVolume non regression test.
=> Fix nonregression test for StatisticsVolume

docs/Installation.md
Update instructions to install development environment
=> Update development installation instructions

Jenkinsfile
=> Edit prefix for brew in mac agents, CI script

Jenkinsfile_nonregression
Fix DWI scheduled tests in Linux and brew prefix in MacOS.
=> Fix prefix path for brew in macOS and DWI test for linux

clinica/iotools/bids_dataset_description.py, clinica/iotools/bids_utils.py, clinica/iotools/converters/habs_to_bids/habs_to_bids.py, clinica/iotools/converters/nifd_to_bids/nifd_utils.py, clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py, clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py, poetry.lock, pyproject.toml
This implementation uses attrs for model definition and cattrs for
serialization.
Closes #430
=> Add model for BIDS dataset description

Jenkinsfile_nonregression
Revert back behavior of cronjob for jenkins compatibility and after comment in PR[533](https://github.com/aramis-lab/clinica/pull/533)
=> Bugfix revert cronjob scheduling format

clinica/pipelines/dwi_dti/dwi_dti_pipeline.py
Remove the thresholding on the DECFA image since it cause  an asymmetry.
=> Remove the  tresholding of the  DECFA image

LICENSE.txt
- Bump year to 2022
- Use HTTPS in URL
=> Update copyright notice in license file

clinica/iotools/utils/pipeline_handling.py
Add more metrics to the output of `merge-tsv`: `thickness` for `t1-freesurfer-longitudinal`, and `MD` `RD` and `AD` for `DWI-DTI`.
=> Add metrics to mergetsv output

poetry.lock, pyproject.toml
Add `pytest-cov` to dev dependencies.
=> Add pytest-cov to generate coverage reports

docs/CAPS/Specifications.md
=> Add section on pet-linear to CAPS specification

pyproject.toml
Update the clinica version in the `pyproject.toml` file to be inline with latest release.
=> Update Clinica version in pyproject.toml

clinica/iotools/utils/data_handling.py, clinica/pipelines/machine_learning_spatial_svm/spatial_svm_utils.py, poetry.lock, pyproject.toml
=> Upgrade dependencies

clinica/iotools/bids_dataset_description.py
See https://github.com/bids-standard/bids-specification/releases/tag/v1.7.0
=> Bump BIDS version to 1.7.0

test/nonregression/pipelines/test_run_pipelines_dwi.py
This PR makes the necessary changes to reactivate the DWI CI tests.
Closes #549
=> Activation of DWI CI tests

clinica/pipelines/pet_linear/pet_linear_cli.py, clinica/pipelines/pet_surface/pet_surface_cli.py, clinica/pipelines/pet_surface/pet_surface_longitudinal_cli.py, clinica/pipelines/pet_surface/pet_surface_utils.py, clinica/pipelines/pet_volume/pet_volume_cli.py, docs/BIDS.md, docs/CAPS/Specifications.md, docs/IO.md, docs/Pipelines/MachineLearning_Classification.md, docs/Pipelines/MachineLearning_PrepareSVM.md, docs/Pipelines/PET_Introduction.md, docs/Pipelines/PET_Linear.md, docs/Pipelines/PET_Surface.md, docs/Pipelines/PET_Surface_Longitudinal.md, docs/Pipelines/PET_Volume.md, docs/Pipelines/Stats_Surface.md, docs/Pipelines/Stats_Volume.md, docs/index.md
Hi!
I found some reminding old convention names in Clinica documentation. They have been adressed in this PR 🤞 
Alexandre
=> Update documentation regarding PET tracers

docs/index.md, mkdocs.yml
=> add ukb documentation entry point

clinica/iotools/utils/data_handling.py
I came across some warnings in my IDE while browsing code.
This PR fixes issues with typos and incomplete docstrings, and removes some dead code. There is also the `Variable referenced before assignment` which is a potentially harmful bug if this code path ever gets triggered at runtime.
=> Fix multiple issues in data_handling module

clinica/utils/atlas.py, clinica/utils/inputs.py
- Correct signature for static methods
- Use lowercase variable names
- Remove dead code
=> Fix warnings in atlas module

clinica/pipelines/t1_freesurfer_atlas/t1_freesurfer_atlas_utils.py, clinica/utils/freesurfer.py
Remove atlas_dictionnary  and use a lsit instead since the keys and values are identical
=> change dict to list for atlases

.gitignore
=> Do not track generated docs

README.md
=> Add badge for supported Python versions

.github/workflows/test.yml, Jenkinsfile, Makefile, clinica/iotools/converters/adni_to_bids/adni_utils.py
Run our unit tests for all supported Python versions.
~~Best would be to merge #680 first.~~
=> Run unit tests on GitHub

CHANGELOG.md, pyproject.toml
=> Updates for release

Jenkinsfile
Update the location of folder that hosts the documentation.
=> Update location of the documentation

clinica/pipelines/dwi_connectome/dwi_connectome_pipeline.py
=> Use ConstrainedSphericalDeconvolution instead of EstimateFOD

clinica/iotools/utils/cli.py, clinica/utils/inputs.py
=> Extend the create-subjects-sessions iotool to CAPS directories

clinica/iotools/utils/data_handling.py
Extracted the relevant portion of issue 701 to make progress. I made sure @ravih18 authorship is preserved.
Closes #701
=> Add pet-linear to checks for missing processing

clinica/iotools/utils/pipeline_handling.py
- Replace `acq` by `trc` 
- Fix pvc_restriction
=> Fix `merge-tsv` according to new PET format

clinica/pydra/engine_utils.py
Small enhancement to the pydra run function to print error message. For debugging purpose.
=> Enh pydra run error msg

clinica/pydra/engine.py, clinica/pydra/engine_utils.py, clinica/pydra/interfaces.py, test/unittests/pydra/test_engine.py
This PR proposes a possible implementation for the CAPS reader to be used with the new Pydra engine. Originally implemented as part of #729 but moved in a separate PR for clarity.
This is very drafty and not tested, but should give a decent idea of the proposed architecture.
Comments and feedbacks are more than welcome as there is clearly room for improvement ! ;)
For PETVolume, this is more or less what the input specs would look like:
```python
input_spec = pydra.specs.SpecInfo(
name="Input",
fields=[
("t1W", str, {"mandatory": True}),
("pet", str, {"mandatory": True}),
(
"mask_tissues",
dict,
{"tissue_number": 1, "modulation": False},
{"mandatory": True},
),
("flow_fields", dict, {"group_label": "group"}, {"mandatory": True}),
("dartel_template", dict, {"group_label": "group"}, …
```
=> CAPS Reader for Pydra Engine

clinica/utils/pet.py, test/unittests/utils/test_pet.py
This PR proposes to refactor the function `clinica.utils.pet.read_psf_information`:
- Add type hints
- Docstring follows Numpydoc conventions
- Refactor code to make it shorter and easier to read
- Add unit tests
=> [REF] Refactor `read_psf_information`

clinica/utils/pet.py, test/unittests/utils/test_pet.py
Same as #748 but for function `get_suvr_mask`
=> [REF] Refactor `get_suvr_mask`

clinica/pipelines/statistics_surface/statistics_surface_pipeline.py, clinica/utils/participant.py
=> Remove function `have_same_subjects`

.jenkins/Jenkinsfile, Makefile, environment.yml
- Add target to check the consistency of the locked dependencies with the project
- Ensure install is run with a consistent lock file
- Add target to refresh the lock file
⚠️  Requires Poetry version 1.2
=> [CI] Improve management of locked dependencies

.github/dependabot.yaml
I have done these updates manually before. Apparently, they are quite easy to automate with `dependabot`.
=> CI: Automate updates of GitHub Actions

clinica/iotools/converters/ukb_to_bids/ukb_utils.py
This PR drops all the unusable folder, which will therefore not be converted.
=> [UKB2BIDS] Drop directories labeled as `unusable`

clinica/pydra/engine_utils.py, clinica/utils/testing_utils.py, test/unittests/pydra/test_interfaces.py, test/unittests/utils/test_utils_inputs.py
This PR proposes to improve the unit tests for the BIDS and CAPS readers developed under the Pydra engine project, which are still poorly tested atm.
=> [TEST] Improve tests for bids and caps readers

docs/CHANGELOG.md, pyproject.toml
Prepare release `0.7.3` of Clinica.
=> Release `0.7.3`

.jenkins/Jenkinsfile
Remove dead code from CI script
=> [CI] Remove deploy stage from Jenkins CI

clinica/iotools/bids_utils.py
Remove unused `compress_nii`:
https://github.com/aramis-lab/clinica/blob/503acbf2bfe73ca92112a064ac731415914ffb57/clinica/iotools/bids_utils.py#L735-L748
=> [MAINT] remove unused `compress_nii`

clinica/iotools/bids_utils.py
Remove unused `get_ext`:
https://github.com/aramis-lab/clinica/blob/503acbf2bfe73ca92112a064ac731415914ffb57/clinica/iotools/bids_utils.py#L724-L732
=> [MAINT] remove unused `get_ext`

clinica/iotools/bids_utils.py
Remove unused `contain_dicom`:
https://github.com/aramis-lab/clinica/blob/503acbf2bfe73ca92112a064ac731415914ffb57/clinica/iotools/bids_utils.py#L634-L650
=> [MAINT] remove unused `contain_dicom`

clinica/iotools/bids_utils.py
Remove unused `compute_new_subjects` : 
https://github.com/aramis-lab/clinica/blob/503acbf2bfe73ca92112a064ac731415914ffb57/clinica/iotools/bids_utils.py#L681-L701
=> [MAINT] remove unused `compute_new_subjects`

clinica/iotools/bids_utils.py
Hopefully enough to fix the issue reported in #786. I did not know about the `on_bad_lines` callback until now.
Closes #786 
Closes #796
=> FIX: Handle erroneous lines when reading AIBL flute metadata

clinica/__init__.py
Disable [etelemetry](https://github.com/sensein/etelemetry-client/blob/master/etelemetry/client.py#L64) requests used by Nipype and Pydra to check for new updates.
Closes #798
=> FIX: Silence telemetry from Nipype and Pydra

.pre-commit-config.yaml
- Upgrade existing hooks to their latest version
- Add hook to run codespell (follow-up to #809)
=> MNT: Update pre-commit hooks setup

clinica/pipelines/__init__.py, clinica/pydra/t1_volume/register_dartel/cli.py, clinica/pydra/t1_volume/register_dartel/pipeline.py, clinica/pydra/t1_volume/tasks.py
Follow-up PR of #768 : 
- Add subcommand to the CLI
- Improve docstring
- Fix `task_prepare_dartel_input_images`
I tried it with these fixes and it seems to work as expected.
=> [FIX] Add pydra register dartel to cli and fix a couple issues

clinica/pydra/engine_utils.py, clinica/pydra/pet_linear/pet_linear_cli.py, clinica/pydra/pet_volume/pet_volume_cli.py, clinica/pydra/t1_linear/t1_linear_cli.py, clinica/pydra/t1_volume/create_dartel/cli.py, clinica/pydra/t1_volume/register_dartel/cli.py, clinica/pydra/t1_volume/tissue_segmentation/cli.py
This PR proposes to expose the number of cores to be used when running Pydra pipelines.
=> [ENH] Expose `n_jobs` to Pydra pipelines

Makefile
Run `make clean` to clear the project tree from generated artifacts.
=> MNT: Add clean target

.jenkins/Jenkinsfile, .jenkins/nonregression_fast.Jenkinsfile, .jenkins/nonregression_slow.Jenkinsfile
Follow-up of #850 
Also update PATH for Mac minis machines where brew is installed in a different location.
=> [CI] Update PATH for MacMinis

test/nonregression/pipelines/test_run_pipelines_ml.py
This non regression test is currently failing on Mac machines : 
https://github.com/aramis-lab/clinica/blob/870eaa620f7e40380e6d0b2095314c5b9d6b7073/test/nonregression/pipelines/test_run_pipelines_ml.py#L134-L137
As can be seen here for instance: https://ci.inria.fr/clinica-aramis/blue/organizations/jenkins/Scheduled%20Tests/detail/dev/146/pipeline/81/
I was able to reproduce on my personal laptop. I believe this is a simple numerical precision error and this PR proposes to slightly change the assertion's tolerance to make the test pass on MACOS.
=> [CI, TEST] Fix precision error in non regression test causing failures on MAC machines

.editorconfig, .jenkins/Jenkinsfile, .jenkins/docs.Jenkinsfile, .jenkins/nonregression_fast.Jenkinsfile, .jenkins/nonregression_slow.Jenkinsfile
- Add editor config rule for Jenkins files
- Apply rule to all Jenkins files
Hopefully this should help fixing other issues with the Jenkins files.
Consistency helps with reading these deeply nested config structures.
=> CI: Apply formatting rules to Jenkins files

clinica/pipelines/statistics_volume_correction/statistics_volume_correction_cli.py
Closes issue https://github.com/aramis-lab/clinica/issues/827
=> [FIX] Fix `statistics-volume-correction` call to `_check_information()`

.jenkins/nonregression_fast.Jenkinsfile
Typos preventing running only the tests specified.
=> [CI] Fix typos in pipeline

clinica/iotools/bids_utils.py, test/unittests/iotools/test_bids_utils.py
This PR proposes to refactor the functions in `clinica/iotools/bids_utils.py`.
WIP...
=> [REF, TEST, DOC] Refactor `clinica.iotools.bids_utils`

clinica/pydra/pet_volume/pipeline.py, clinica/pydra/query.py, clinica/pydra/shared_workflows/smoothing.py, clinica/pydra/t1_volume/__init__.py, clinica/pydra/t1_volume/dartel2mni/__init__.py, clinica/pydra/t1_volume/dartel2mni/cli.py, clinica/pydra/t1_volume/dartel2mni/pipeline.py, clinica/pydra/t1_volume/dartel2mni/tasks.py, clinica/pydra/utils.py, test/unittests/pydra/t1_volume/dartel2mni/test_tasks.py, test/unittests/pydra/test_utils.py
This PR proposes a Pydra-based implementation of the pipeline `t1-volume-dartel2mni`.
=> Pydra implementation of T1Volume-Dartel2MNI

clinica/pipelines/pet_surface/pet_surface_utils.py, clinica/pipelines/pet_volume/pet_volume_utils.py, clinica/utils/filemanip.py, test/unittests/utils/test_filemanip.py
=> [FIX] Handle 4D images with dummy fourth dimension

clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_workflows.py
=> Remove unused `ApplyXFM` node from EPI pipeline

docs/CHANGELOG.md, pyproject.toml
Prepare release `0.7.4` of Clinica.
=> Release `0.7.4`

.jenkins/Jenkinsfile, .jenkins/nonregression_fast.Jenkinsfile, test/nonregression/pipelines/test_run_pipelines_stats.py
Follow-up PR of #885 
This PR proposes to run the two statistics tests relying on SPM within the same group to avoid race conditions when running the test suite in parallel.
=> [TEST] run MATLAB based tests in same group

.jenkins/nonregression_fast.Jenkinsfile
Fix error in daily non regression tests pipeline introduced in #886.
=> [CI] Fix daily non regression tests Jenkinsfile

clinica/iotools/converters/adni_to_bids/adni_utils.py
This PR fixes a viscode error occuring with the new clinical data.
=> [ADNI] Fix viscode error

clinica/iotools/converters/adni_to_bids/adni_utils.py
Added some more tests, since it seems like the `uns1` problem is general.
=> [ADNI] Fix uns1 issue

clinica/pydra/pet_volume/pipeline.py, poetry.lock, pyproject.toml
~~Requires a new release of `pydra-petpvc` exposing the PSF's FWHM in x, y and z directions as separate arguments.~~
=> REF: Use PETPVC task from pydra-petpvc

clinica/utils/nipype.py, test/unittests/utils/test_nipype.py
Small PR to add some unit tests for the function `clinica.utils.nipype.container_from_filename`.
Also make the docstring Numpydoc-compliant.
=> [TEST] Add unit tests for function `container_from_filename`

docs/CHANGELOG.md, pyproject.toml
Requires #934 
Prepare release `0.7.5` of `Clinica`.
=> Release `0.7.5`

.jenkins/nonregression_fast.Jenkinsfile
Investigate current failure on Linux machines for daily non regression tests which looks like a data race issue.
=> [CI] try running anat daily non regression tests sequentially on Linux

clinica/iotools/converters/adni_to_bids/adni_json.py, test/unittests/iotools/converters/adni_to_bids/test_adni_json.py
=> [FIX] Fix BIDS violations in  adni to bids converter

environment.yml
This PR proposes to use the Conda package for MRtrix3: https://anaconda.org/MRtrix3/mrtrix3
=> [INFRA] Add `MRtrix3` to conda environnement

clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_utils.py
=> [FIX] DWI preprocessing using T1 pipeline not generating bvec file

docs/CHANGELOG.md, pyproject.toml
Prepare release `0.7.6` of Clinica.
=> Release `0.7.6`

clinica/iotools/converters/aibl_to_bids/utils/bids.py, test/unittests/iotools/converters/aibl_to_bids/test_aibl_utils.py
Should fix errors occurring in #978
=> [TEST] Make unit test deterministic

clinica/pydra/dwi/_commons/__init__.py, clinica/pydra/dwi/_commons/_tasks.py, clinica/pydra/dwi/_commons/_workflows.py, poetry.lock, pyproject.toml
This PR proposes to port to Pydra the DWI workflow `eddy_fsl_pipeline`:
https://github.com/aramis-lab/clinica/blob/988f611d5bd3f9cdf9f23aeafbad1d85fba085e5/clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_workflows.py#L4-L12
=> [Pydra] Port DWI `eddy_fsl_pipeline` to Pydra

.github/workflows/test_non_regression_fast.yml
Simple PR changing names of steps in the non regression workflow (otherwise this is pretty confusing in the GitHub UI).
=> [INFRA] Fix bad names in non regression workflow

clinica/pipelines/cli_param/option.py
=> [FIX] fix `reconstruction_method` CLI option

clinica/iotools/utils/data_handling.py
Fix a bug introduced in #1013 
I merged #1013 without realizing that one of the non regression test for the IOtools was broken. This should fix it.
=> [FIX] Fix `_create_merge_file_from_bids`

docs/CHANGELOG.md, pyproject.toml
Prepare release `0.7.7` of Clinica.
=> Release `0.7.7`

.github/workflows/test_non_regression_fast.yml
=> [CI] Run SPM based non regression tests in the same process

clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fmri.py, clinica/iotools/converters/adni_to_bids/adni_to_bids.py
=> [ADNI] Allow convert fmri multiband

docs/ClinicaConferences.md
=> [DOC] Add entry in documentation for NOW 2023

clinica/iotools/utils/data_handling.py, clinica/pipelines/engine.py, clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_longitudinal_cli.py, clinica/pipelines/t1_volume/t1_volume_cli.py, clinica/pydra/interfaces.py, clinica/utils/participant.py, test/unittests/utils/test_participant.py
Fixes #1051 
Also proposes to refactor and clean the code the participant utils, and adds unit tests for these functions.
=> Fix `get_subject_session_list` return value

clinica/pipelines/dwi_dti/dwi_dti_pipeline.py, clinica/utils/dwi.py, clinica/utils/input_files.py, test/unittests/utils/test_input_files.py, test/unittests/utils/test_utils_inputs.py
=> [ENH] Allow the clinica file reader to read dwi dti images

.github/workflows/test.yml, .github/workflows/test_non_regression_fast.yml, clinica/iotools/utils/data_handling.py
Let's try the new M1 runners introduced by GitHub: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
=> [CI] Run unit tests on new GitHub M1 runners

clinica/pipelines/dwi_connectome/dwi_connectome_pipeline.py, clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_utils.py, clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_utils.py, clinica/utils/dwi.py, clinica/utils/input_files.py, test/nonregression/pipelines/test_run_pipelines_dwi.py, test/unittests/utils/test_dwi.py
Fixes #614 
Requires data PR https://github.com/aramis-lab/clinica_data_ci/pull/52
=> Improve BIDS compliance for preprocessed DWI files

test/nonregression/pipelines/dwi/preprocessing/test_phase_diff.py
Fixes missing argument in non regression tests (bug introduced in #1076).
=> [FIX] Fix forgotten argument in non regression tests

.pre-commit-config.yaml, clinica/pipelines/statistics_volume/statistics_volume_utils.py, pyproject.toml
pre-commit: v4.4.0 -> v4.5.0
ruff: v0.1.7 -> v0.2.2
=> [MAINT] Bump pre-commit hooks

clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_longitudinal_correction_pipeline.py, clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_template_pipeline.py
Fix a bug introduced when moving to pathlib to model file paths in pipelines.
They need to be converted to strings when used through a Nipype interface.
=> [FIX] Some fixes to T1Freesurfer longitudinal pipelines

clinica/pipelines/machine_learning/algorithm.py
Value "auto" is no longer accepted since sklearn version 1.1, the default value is now "sqrt".
This commit:
- Implements the necessary translation from "auto" to "sqrt";
- Refactors the piece of code instantiating the classifier;
- Extracts the normalization code to a separate utility.
=> [BUG] Fix regression with max_features in sklearn

clinica/pipelines/pet_surface/pet_surface_pipeline.py, clinica/pipelines/pet_surface/pet_surface_utils.py, clinica/pipelines/pet_volume/pet_volume_pipeline.py, clinica/pipelines/statistics_volume/statistics_volume_utils.py, clinica/pipelines/t1_volume_create_dartel/t1_volume_create_dartel_pipeline.py, clinica/pipelines/t1_volume_dartel2mni/t1_volume_dartel2mni_pipeline.py, clinica/pipelines/t1_volume_register_dartel/t1_volume_register_dartel_utils.py, clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py, clinica/pydra/pet_volume/pipeline.py, clinica/pydra/statistics_volume/pipeline.py, clinica/pydra/statistics_volume_correction/pipeline.py, clinica/pydra/t1_volume/dartel2mni/pipeline.py, clinica/utils/spm.py, test/unittests/utils/test_spm.py
=> [TEST] Add tests and refactor SPM standalone configuration functions

docs/CAPS/Introduction.md, docs/CAPS/Specifications.md, docs/Pipelines/T1_Linear.md, docs/Pipelines/T1_Volume.md
Make some updates to the documentation related to CAPS format (3 digits session labels, dwi suffix...)
=> [DOC] Some updates to the CAPS documentation

docs/Pipelines/Stats_Surface.md
Closes #980 
Rendered documentation page: https://aramislab.paris.inria.fr/clinica/docs/public/PR-1100/Pipelines/Stats_Surface/
=> [DOC] Update documentation for statistics surface pipeline

docs/CAPS/Specifications.md, docs/glossary.md
=> [DOC] Add FWHM definition to glossary

docs/Pipelines/MachineLearning_PrepareSVM.md, docs/glossary.md
=> [DOC] Add SUVR definition in glossary

docs/Pipelines/PET_Introduction.md, docs/glossary.md
=> [DOC] Add PVC definition to glossary

clinica/pipelines/t1_linear/anat_linear_utils.py
=> [MAINT] Change to use str.removesuffix

clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fdg_pet.py, test/unittests/iotools/converters/adni_to_bids/adni_modalities/test_adni_fdg_pet.py
=> [MAINT] Change to regex for subject conversation to RID + tests

clinica/iotools/bids_readme.py, clinica/iotools/bids_utils.py, clinica/iotools/converters/adni_to_bids/adni_to_bids.py, clinica/iotools/converters/aibl_to_bids/aibl_to_bids.py, clinica/iotools/converters/aibl_to_bids/utils/clinical.py, clinica/iotools/converters/genfi_to_bids/genfi_to_bids.py, clinica/iotools/converters/habs_to_bids/habs_to_bids.py, clinica/iotools/converters/nifd_to_bids/nifd_to_bids.py, clinica/iotools/converters/oasis3_to_bids/oasis3_to_bids.py, clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py, clinica/iotools/converters/ukb_to_bids/ukb_to_bids.py, test/unittests/iotools/test_bids_utils.py
This PR proposes to use an enumeration for datasets that can be converted by clinica.
=> [REF] Encode names of dataset as an enum

clinica/utils/filemanip.py, clinica/utils/participant.py, test/unittests/utils/test_filemanip.py, test/unittests/utils/test_participant.py
=> [MAINT] Move read_participant_tsv function and make it private

.github/workflows/lint.yaml, .github/workflows/test.yml, .github/workflows/test_converters.yml, .github/workflows/test_instantiation.yml
=> [CI] Run CI on maintenance branches

docs/CHANGELOG.md, pyproject.toml
Prepare release `0.8.1` of Clinica.
=> Release `0.8.1`

LICENSE.txt, clinica/iotools/converters/oasis3_to_bids/oasis3_to_bids.py, clinica/iotools/converters/oasis3_to_bids/oasis3_to_bids_cli.py, clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py, clinica/iotools/converters/oasis_to_bids/oasis_to_bids_cli.py, docs/Converters/OASIS2BIDS.md, docs/Converters/OASIS3TOBIDS.md
=> [MAINT] Update OASIS website URL

clinica/utils/image.py
=> [ENH] Add crop_nifti to public API

clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fdg_pet.py, ignore_words.txt, pyproject.toml
Wrong preprocessing sequence for "STEP4_8MM" and "STEP4_6MM".
Results: Impossible to create a BIDS of PET images preprocessed step 4.
Fix issue #1157
=> ADNI_to_BIDS : PET : Wrong preprocessing sequence --> Results: Impossible to make bids of FDG PET : Uniform

clinica/iotools/bids_dataset_description.py, clinica/utils/inputs.py, test/unittests/utils/test_utils_inputs.py
=> [ENH] Unify DatasetType class

clinica/iotools/bids_utils.py
=> [FIX] Fix inconsistent logging in function `run_dcm2niix`

clinica/pipelines/machine_learning/ml_utils.py
=> [FIX] Fix calls to `matplotlib.cm.get_cmap`

clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fmap.py
Remove unused function in ADNI-2-BIDS, field maps modality.
=> [MAINT] Remove function BidsGuess

test/unittests/utils/test_atlas.py
=> [TEST] Mock remote atlases in unit tests

clinica/pipelines/pet_linear/pet_linear_pipeline.py, clinica/pipelines/t1_linear/anat_linear_pipeline.py, clinica/pipelines/tasks.py, clinica/pydra/pet_linear/pipeline.py, clinica/pydra/pet_linear/tasks.py, clinica/pydra/t1_linear/t1_linear.py, clinica/utils/filemanip.py, clinica/utils/image.py, test/unittests/utils/test_image.py
=> [FIX] Fix function `crop_nifti` to perform cropping instead of resampling

clinica/iotools/bids_utils.py, clinica/iotools/converters/adni_to_bids/adni_json.py, clinica/iotools/converters/adni_to_bids/adni_to_bids.py, clinica/iotools/converters/adni_to_bids/adni_utils.py, clinica/iotools/converters/aibl_to_bids/utils/bids.py, clinica/iotools/converters/aibl_to_bids/utils/clinical.py, clinica/iotools/converters/genfi_to_bids/genfi_to_bids_utils.py, clinica/iotools/converters/habs_to_bids/habs_to_bids.py, clinica/iotools/converters/nifd_to_bids/nifd_utils.py, clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py, clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py, clinica/iotools/converters/ukb_to_bids/ukb_utils.py, clinica/iotools/utils/data_handling.py, test/unittests/iotools/converters/adni_to_bids/test_adni_json.py, test/unittests/iotools/test_bids_utils.py
Add a function translating source/study ids to bids ids.
=> [ENH] Proposition of a function to translate study ids to bids ids

clinica/iotools/converters/nifd_to_bids/nifd_utils.py
This PR modifies a check on the type of a data frame to adapt it to data changes.
=> [FIX] Change check on type in converter NIFD 

clinica/pipelines/dwi/preprocessing/t1/pipeline.py, clinica/pipelines/dwi/preprocessing/t1/utils.py, clinica/pipelines/dwi/preprocessing/utils.py, clinica/pipelines/dwi/preprocessing/workflows.py, clinica/pipelines/engine.py, test/unittests/pipelines/dwi/preprocessing/test_t1_utils.py
=> [FIX] Fixes DWI preprocessing using T1 when images are 3D

docs/CHANGELOG.md, pyproject.toml
Prepare release `0.8.2` of Clinica.
=> Release `0.8.2`

clinica/pipelines/engine.py, test/unittests/pipelines/test_nipype_engine.py
=> [FIX] Fix cross sectional to longitudinal conversion logic

docs/CHANGELOG.md, pyproject.toml
Prepare release `0.8.3` of Clinica.
=> Release `0.8.3`

clinica/iotools/utils/pipeline_handling.py
Fix broken import due to post-release `0.8.3` merge.
The function `replace_sequence_chars` has been moved since then in another module.
=> [FIX] Fix broken import

docs/Pipelines/DWI_Connectome.md, docs/Third-party.md
=> [DOC] Add FreeSurfer dependency to dwi-connectome documentation

docs/CHANGELOG.md, pyproject.toml
Prepare release `0.8.4` of Clinica.
=> Release `0.8.4`

README.md
Replace CI-inria broken badge with unit test status badge.
=> [MAINT] Replace broken badge in README

clinica/pipelines/machine_learning_spatial_svm/spatial_svm_utils.py
Follow up for #1263 
`np.complex_` has been removed in Numpy 2.
=> [FIX] Fix numpy deprecation

clinica/iotools/bids_utils.py, clinica/iotools/converters/adni_to_bids/adni_utils.py, clinica/iotools/converters/cli.py, clinica/iotools/converters/factory.py, clinica/iotools/converters/ixi_to_bids/__init__.py, clinica/iotools/converters/ixi_to_bids/ixi_to_bids.py, clinica/iotools/converters/ixi_to_bids/ixi_to_bids_cli.py, clinica/iotools/converters/ixi_to_bids/ixi_to_bids_utils.py, clinica/pipelines/t1_linear/anat_linear_utils.py, test/unittests/iotools/converters/ixi_to_bids/test_ixi_to_bids_utils.py, test/unittests/iotools/test_bids_utils.py
This PR adds a new converter for the IXI dataset. It covers the implementation and the unit testing only, since non regression tests and documentation will be added in other PRs.
=> [CONV] Implementing new converter for IXI dataset

test/nonregression/pipelines/anat/test_t1_freesurfer.py
Same as #1253 but for `T1Freesurfer` pipeline.
=> [FIX] Skip question when testing `T1Freesurfer` pipeline

test/nonregression/iotools/test_run_converters.py
Revert #1282 now that https://github.com/aramis-lab/clinica_data_ci/pull/70 is merged.
=> [TEST] Put `ixi-to-bids` test back

.github/workflows/test_non_regression_fast.yml, clinica/pipelines/statistics_volume/statistics_volume_pipeline.py, clinica/pipelines/statistics_volume/statistics_volume_utils.py, clinica/utils/check_dependency.py, clinica/utils/spm.py, test/nonregression/pipelines/test_run_pipelines_stats.py, test/nonregression/testing_tools.py, test/unittests/utils/test_check_dependency.py, test/unittests/utils/test_spm.py
This PR proposes to fix a few bugs around statistics pipeline relying on SPM, captured by the "fast" non regression test suite.
=> [FIX] Fix `get_spm_version`

docs/CHANGELOG.md, pyproject.toml
Prepare release `0.9.1` of Clinica.
=> Release `0.9.1`

CONTRIBUTING.md
=> [DOC] Update contributing guidelines

.github/workflows/test.yml
=> [CI] Replace `macos-12` GitHub runner image

clinica/iotools/converters/aibl_to_bids/utils/bids.py, clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py
=> [FIX] Fix logging in OASIS and AIBL converters

docs/CHANGELOG.md, pyproject.toml
Prepare release `0.9.2` of Clinica.
=> Release `0.9.2`

.github/workflows/build_and_deploy.yml
=> [CI] Build and deploy documentation on master

docs/Atlases.md, docs/Pipelines/Stats_Surface.md, docs/WhatIsClinica.md
Also did some consistency fixes in casing and punctuation.
ref
- #1363
=> Fix indentations (must have 4 spaces for mkdocs to render properly)

docs/CHANGELOG.md, pyproject.toml
Prepare release `0.9.3` of Clinica.
=> Release `0.9.3`

clinica/pipelines/dwi/dti/utils.py, clinica/utils/dwi.py, clinica/utils/input_files.py, test/nonregression/pipelines/dwi/test_pipelines.py, test/unittests/utils/test_input_files.py, test/unittests/utils/test_utils_inputs.py
=> [FIX] Fix circular import with `DTIBasedMeasure` enumeration

README.md
=> [DOC] Fix broken link in readme

docs/glossary.md, docs/snippets/abbreviations.md
MRI term and definition added from Wikipedia. 
Closes #1384
=> Add term MRI in the glossary 

.github/workflows/test.yml, clinica/pipelines/dwi/connectome/utils.py, test/unittests/pipelines/dwi/test_connectome_utils.py
- Temporary fix for poetry after 2.0.0 release
- Update MRTRIX3 sha256 codes (only modification : license year)
=> [FIX] Fix unit tests

test/nonregression/iotools/test_run_converters.py, test/nonregression/testing_tools.py, test/unittests/test_testing_tools.py
Only for AIBL for now
Need to change CI data
=> [TEST] Add non-regression tests for AIBL that compares the inside of all metadata tsv files

test/nonregression/pipelines/anat/test_t1_linear.py, test/nonregression/testing_tools.py, test/unittests/test_testing_tools.py
Adds a function that checks inside the nifti files, only in T1 Linear for now (to extend if code validated).
=> [TEST] Add non-regression tests to anat pipelines

.pre-commit-config.yaml, poetry.lock, pyproject.toml
=> [MAINT] Update `pyproject.toml`

docs/Pipelines/FLAIR_Linear.md
Rewrite the page in a similar way to T1-Linear with options behind a little clearer.
=> [DOC] FLAIR documentation update

docs/Pipelines/FLAIR_Linear.md, docs/glossary.md
=> [DOC] MNI term added to documentation glossary

docs/Pipelines/FLAIR_Linear.md, docs/Pipelines/T1_Linear.md, docs/glossary.md
Follow-up for #1452 
Fixing the paths to glossary references for MNI occurrences.
=> [FIX] Fixing paths to glossary references for MNI term occurrences

test/unittests/converters/test_converter_utils.py
=> [TEST] Add unit tests for function get_sessions_from_bids_dataset

README.md
Fix all the http URLs to be https.
=> [DOC] Fix image URLs in README

clinica/converters/oasis_to_bids/_converter.py, clinica/converters/oasis_to_bids/_utils.py, test/unittests/converters/test_oasis_to_bids_utils.py
=> [REF][TEST] OASIS-to-BIDS : Tested function created to move code for finding .img file from _converter to _utils module

test/nonregression/test_run_converters.py, test/nonregression/testing_tools.py
Extends non regression tests to metadata files as part of https://github.com/aramis-lab/clinica/issues/1450.
=> [TEST] OASIS-to-BIDS : add non-regression tests for metadata files

clinica/converters/oasis_to_bids/_converter.py, clinica/converters/oasis_to_bids/_utils.py, test/unittests/converters/test_oasis_to_bids_utils.py
=> [TEST] OASIS-to-BIDS : Function moved and test added to get_image_with_good_orientation

test/nonregression/test_run_converters.py
Extended non-regression tests for metadata files as part of #1450
=> [TEST] HABS-to-BIDS : Add comparison of metadata files in non-regression tests

test/nonregression/test_run_converters.py
Extended non-regression tests for metadata files as part of #1450
=> [TEST] OASIS3-to-BIDS : Add comparison of metadata files in non-regression tests

clinica/iotools/bids_utils.py, docs/CHANGELOG.md, pyproject.toml
Prepare release `0.9.4` of Clinica.
=> Release `0.9.4`

.github/workflows/test_non_regression_fast.yml, .github/workflows/test_pipelines_anat.yml, .github/workflows/test_pipelines_dwi_preprocessing.yml, .github/workflows/test_pipelines_pet.yml
Also modified temporarily the cron of the anat pipelines to trigger today.
=> [CI] Use SPM standalone instead of SPM on CI

clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py, clinica/utils/spm.py, test/unittests/utils/test_check_dependency.py, test/unittests/utils/test_spm.py
Adresses part of #1481 regarding `_get_platform_dependant_matlab_command_for_spm_standalone`.
Rq : not sure it will do well with CI set-up
=> [REF] Search for SPM standalone execution file with pattern instead of hardcoding for spm12

clinica/utils/spm.py, test/unittests/utils/test_spm.py
=> [FIX] Fix bad fstring in unit test

clinica/converters/oasis_to_bids/_converter.py, clinica/converters/oasis_to_bids/_utils.py, test/unittests/converters/test_oasis_to_bids_utils.py
=> [REF] OASIS-to-BIDS : moving parts of the code that performs data modification from _converter to _utils

docs/Software/Third-party.md
Closes #1493 
TODO : Can we find spm12 standalone to download somewhere ? maybe with cat12 ?
=> [DOC] Complete the documentation about SPM12 standalone set-up

.github/workflows/test_non_regression_fast.yml, .github/workflows/test_pipelines_anat.yml, .github/workflows/test_pipelines_dwi_preprocessing.yml, .github/workflows/test_pipelines_pet.yml
Revert #1486 while we work on #1491
=> [CI] Revert PR 1486

clinica/converters/genfi_to_bids/_converter.py
=> [FIX] GENFI-to-BIDS : validates `path_to_clinical` only if exists

clinica/converters/adni_to_bids/_converter.py, clinica/converters/adni_to_bids/_utils.py, clinica/converters/adni_to_bids/cli.py, clinica/converters/adni_to_bids/modality_converters/_av45_fbb_pet.py, clinica/converters/adni_to_bids/modality_converters/_dwi.py, clinica/converters/adni_to_bids/modality_converters/_fdg_pet.py, clinica/converters/adni_to_bids/modality_converters/_flair.py, clinica/converters/adni_to_bids/modality_converters/_fmap.py, clinica/converters/adni_to_bids/modality_converters/_fmri.py, clinica/converters/adni_to_bids/modality_converters/_pib_pet.py, clinica/converters/adni_to_bids/modality_converters/_t1.py, clinica/converters/adni_to_bids/modality_converters/_tau_pet.py
Closes #1461 
Documentation needs to be changed since the option use has changed.
=> [REF] ADNI-to-BIDS : Keeping parameter mod_to_update instead of force-new-extraction option

test/nonregression/pipelines/dwi/test_pipelines.py
As shown by this [failed](https://github.com/aramis-lab/clinica/actions/runs/15076589070/job/42385326655) test, scripts for DWI pipelines tests needed to be updated.
=> [FIX][TEST] Fix bids module import in DWI test scripts

clinica/converters/_utils.py, clinica/converters/oasis_to_bids/_converter.py, clinica/converters/oasis_to_bids/_utils.py, test/unittests/converters/test_converter_utils.py, test/unittests/converters/test_oasis_to_bids_utils.py
=> [BUG] OASIS-to-BIDS informative logs made more relevant based on --subjects_list option

environment.yml
=> Remove defaults channel from `environment.yml` file

clinica/converters/_utils.py, clinica/converters/habs_to_bids/_converter.py, clinica/converters/nifd_to_bids/_utils.py, test/unittests/converters/test_converter_utils.py
=> [REF] Factorizing ```install_nifti```

clinica/converters/genfi_to_bids/_utils.py, test/unittests/converters/test_genfi_to_bids_utils.py
=> [REF] GENFI-To-BIDS : Separation of ```write_bids``` into 3 functions and tests added
