aramis-lab/clinica

- clinica/iotools/bids_utils.py
- clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py
- remove duplicates from participants.tsv
- ensure that the image converted corresponds to the alternative_id_1
> Remove duplicates during oasis-to-bids conversion

- clinica/iotools/bids_utils.py
- clinica/iotools/utils/pipeline_handling.py
- clinica/pipelines/pet_surface/pet_surface_utils.py
- clinica/pipelines/t1_volume_existing_template/t1_volume_existing_template_pipeline.py
- clinica/pipelines/t1_volume_existing_template/t1_volume_existing_template_utils.py
This pull request make some modification to allow the pipeline `T1VolumeExistingTemplate` to fail for some subjects without affecting the others. 
The files are grabbed with the use of `glob`, allowing to have a list of input files, eventually leading to the utilization of `iterables`.
The main problem to deal with were the containers of the datasink. A trick had to be found. Container variable of datasink is now linked to input T1w file through a function that give away the container name based on the filename.
Work to do left (but not necessary for this merge request) :  
- replace MapNode by node when necessary.
- @alexandreroutier needs to test wether the intended behavior is working (crash on one of the file : do the other keep running ?
Attached : 
- new diagram
- working directory …
> t1-volume-existing-template update with iterables 

- clinica/pipelines/t1_volume_dartel2mni/t1_volume_dartel2mni_pipeline.py
- clinica/pipelines/t1_volume_existing_template/t1_volume_existing_template_pipeline.py
- clinica/pipelines/t1_volume_new_template/t1_volume_new_template_pipeline.py
- clinica/pipelines/t1_volume_parcellation/t1_volume_parcellation_pipeline.py
- clinica/pipelines/t1_volume_parcellation/t1_volume_parcellation_utils.py
- clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py
- test/instantiation/test_instantiate_all_pipelines.py
- test/nonregression/test_run_pipelines.py
This PR aims to fix some `t1-volume`  pipelines after the removal of `atlas_statistics`  function in `t1_volume_dartel2mni` folder (this function was duplicated in `t1_volume_parcellation` folder). 
Signature of the function changed which made nodes calling it crashed.
It also fix CI functions regarding t1-freesurfer-longitudinal pipeline.
TODO: Upload CI data for T1FreeSurferLongitudinal on each CI machine.
> Fix t1-volume pipelines and CI path for t1-freesurfer-longitudinal pipeline

- clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py
When a machine has only one core, `Pool(cpu_count() - 1)` is replaced by `Pool(max(os.cpu_count()-1, 1))` to avoid `Pool(0)`.
> Fix OASIS-2-BIDS when computer has 1 core (Issue #22)

- test/nonregression/test_run_pipelines.py
The previous threshold was adapted for Mac (the ref/ data were generated for Mac) but it turns out that non regression tests could not be reproduced on Linux.
> Adapt CI threshold for DWIConnectome

- test/nonregression/test_run_iotools.py
This PR includes new PET tracers for non ADNI-2-BIDS regression tests.
Data on CI machines are currently updated.
> Add new modalities for ADNI-2-BIDS CI

- clinica/resources/templates/pipeline_template/cli.py.j2
Update of the file `clinica/resources/templates/pipeline_template/cli.py.j2` to take into account pipeline categories created by @alexandreroutier a few months ago.
I hope this is what was expected in the airtable card `[CLI] Update CLI template with the command line categories`
> Add categories for CLI when creating a pipeline with `clinica generate`

- clinica/pipelines/pet_surface/pet_surface_pipeline.py
- clinica/pipelines/pet_surface/pet_surface_utils.py
pet-surface can now be used with SPM standalone on mac and Linux (tested on latest version of SPM standalone for mac and linux, and MCR v713 for mac and MCR v2018b for linux)
SPM standalone is used when `SPMSTANDALONE_HOME` and `MCR_HOME` are found in the `os.environ.keys()`
The key idea is to create a batch file that SPM can read. The command to run a batch file with spm standalone is :
`$SPMSTANDALONE_HOME/run_spm12.sh /path/to/MCR batch /path/to/batch/file.m`
BUT :  
In Mac Os : the script `run_spm12.sh` must be run from its very own folder, leading to a command like : 
`cd $SPMSTANDALONE_HOME && ./run_spm12.sh /path/to/MCR batch /path/to/batch/file.m`  
The batch file is created on the fly when the function `runApplyInverseDeformationField_SPM_standalone` is run.
The file …
> pet-surface update for docker

- clinica/cmdline.py
- clinica/iotools/converters/adni_to_bids/adni_utils.py
- clinica/iotools/utils/data_handling.py
- clinica/iotools/utils/data_handling_cli.py
- test/nonregression/test_run_iotools.py
- test/test_coding_style.py
This PR aims to provide an IO tool that allows the user to center all the Niftis of a BIDS directory.
Currently, this goes as follows : cmdline interface takes 2 inputs : `bids_directory` and `output_bids_directory`
- `bids_directory` is copied in `output_bids_directory`
- Each nifti file of `output_bids_directory` is replaced by its centered version
A bunch of checks are performed:
- check that `bids_directory` is an actual BIDS.
- if some files exist in `output_bids_directory`, we tell the user about it and ask him if he wants to continue anyway, knowing that some files may be erased.
If errors happen, they are all stored until each nifti files are treated. Then, all errors are displayed to the user.
With -v arg :
Otherwise :
> Center nifti

- clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_pipeline.py
- clinica/utils/mri_registration.py
The two commits fix issues met in CI namely:
- Too long path in `dwi-preprocessing-using-t1`
- Exceptions due to relative path in `mri_registrations.py`
> Fix CI for DWI* pipelines

- clinica/iotools/utils/data_handling.py
Fix bug in center-nifti caused by nib.save.
If destination file already exists, nib.save crashes
> Fix bug in center-nifti caused by nib.save

- clinica/resources/templates/pipeline_template/cli.py.j2
Typo that prevents the pipeline from working.
> Fix typo in pipeline generation

- clinica/pipelines/engine.py
- clinica/pipelines/machine_learning_spatial_svm/spatial_svm_cli.py
- clinica/pipelines/machine_learning_spatial_svm/spatial_svm_pipeline.py
- clinica/utils/atlas.py
- clinica/utils/check_dependency.py
- clinica/utils/exceptions.py
- clinica/utils/freesurfer.py
- clinica/utils/group.py
- clinica/utils/input_files.py
- clinica/utils/inputs.py
- clinica/utils/participant.py
- clinica/utils/spm.py
- clinica/utils/statistics.py
- clinica/utils/stream.py
- clinica/utils/ux.py
- test/instantiation/test_instantiate_all_pipelines.py
- test/nonregression/test_run_pipelines.py
Hi,
This PR contains the following small modifications:
- Clarify how to deactivate `How many threads.. message`
- Add modules description in utils/ folder.
- Change how input data are chosen in ML-Prepare-Data. Flags for `Pipeline options if you use inputs from pet-volume pipeline:` will be updated in another PR
Alex
> Clarifications and change how input data are grabbed for ML-Prepare-Data

- clinica/pipelines/t1_linear/t1_linear_cli.py
- clinica/pipelines/t1_linear/t1_linear_pipeline.py
- test/instantiation/test_instantiate_all_pipelines.py
- test/nonregression/test_run_pipelines.py
From now, the pipeline crops the input image using the template. 
If the option `--uncropped_image` is added to the command line, the image is not cropped.
> Update T1 linear default behavior

- clinica/pipelines/t1_linear/t1_linear_cli.py
- clinica/pipelines/t1_linear/t1_linear_pipeline.py
- clinica/pipelines/t1_linear/t1_linear_utils.py
- setup.py
This PR contains:
- Add get_processed_images method. This ables to
* Ignore & Display image(s) already present in CAPS folder
* Display failed image(s) when running t1-linear pipeline
- Print end message when an image has finished
- Fix Issue #102
> Display failed image(s) when running t1-linear pipeline

- test/nonregression/test_run_pipelines.py
This PR removes copy of empty CAPS folder non-regression tests for `t1-linear` pipeline.
> Remove copy of empty CAPS folder

- requirements.txt
Bound version of xldr in the requirements file (>=1.2.0, < 2.0.0). From version 2.0.0, XLXS file are not supported ([see here](https://github.com/pandas-dev/pandas/issues/38410)).
> Bound xldr version to use a package before the 2.0.0 version

- clinica/iotools/converter_utils.py
- clinica/iotools/utils/data_handling.py
This PR intends to add a longitudinal analysis in `check-missing-modality`.
Maybe it should be done in another iotool, but the reason it was done in `check-missing-modality` is that it uses the outputs of this function.
> Add longitudinal analysis

- clinica/pipelines/pet_volume/pet_volume_pipeline.py
- clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py
Bugfix detected in non-regression test for `PETVolume` and  `T1VolumeTissueSegmentation`: wrong input name for nipype nodes when using the `container_from_file()` function.
> Bugfix when using a nipype node with the container_from_file() function

- docs/index.md
[Doc] Change the order in which the "Machine Learning" and "Deep Learning" sections appear in the documentation so as to correspond to the order in the clinica paper.
> Invert ML and DL sections' order in documentation

- clinica/utils/inputs.py
Fix issue #169 by replacing exception by warning message if the CAPS directory structure was not recognized.
> Replace exception by warning in determine_caps_or_bids

- requirements.txt
I know the nipype team is actively working on the next major version of nipype. We might want to avoid accidental updates to it considering it's a critical dependency.
> Restrict nipype updates to the current major version

- requirements.txt
Pydicom dependency was recently introduced but the package was not added to the requirements file. Closes #228.
> Add pydicom to the requirements file

- docs/Third-party.md
Installing MRtrix3 with Homebrew is quite a pain on Big Sur.
It requires XCode and Qt5, which are quite significant in size, and users may get this unwelcoming error message if XCode is not setup properly:
`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`
I have updated our docs to point towards the official channels recommended upstream.
> docs: Update instructions for MRtrix3

- requirements-dev.txt
Fix version for `numpy` and `nipy` in order to solve temporary installation of the latter package in MacOS CI machines.
> Update requirements from dev to install nipy in macOS

- clinica/iotools/converters/aibl_to_bids/aibl_to_bids_cli.py
There is no such option in the AIBL converter CLI. I guess it came from a copy-pasta of the ADNI one, where this option is available.
> Remove reference to --force_new_extraction in AIBL converter CLI

- clinica/engine/cmdparser.py
My IDE flagged `get_cmdparser_objects` as unreferenced and so is the wrapping function.
> Remove dead code in cmdparser module

- clinica/iotools/bids_utils.py
Missing else branch may lead to `f_type`key being undefined.
Add a `continue` statement to keep iterating nonetheless.
> Add missing else branch to scan file writer

- clinica/compat.py
- clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_template_utils.py
- clinica/utils/check_dependency.py
Required to maintain compatibility with Python versions older than 3.7.
Having compatibility code in `<package>/compat.py` is pretty standard.
> Add compat module for errno

- clinica/pipelines/machine_learning_spatial_svm/spatial_svm_cli.py
Bug introduced by an incomplete renaming of an argument (cc @mdiazmel).
> Fix unresolved reference in SVM pipeline

- clinica/iotools/utils/cli.py
The optional argument "pipelines" was missing an 's' and thus causing Clinica to crash when invoking merge-tsv
> Fix typo in merge_tsv CLI

- clinica/iotools/utils/cli.py
After discussion with @ghisvail, specifying the target var explicitly seems to be a better option as the pipelines are specified one by one.
> Add merge_tsv() required target var in CLI

- clinica/iotools/utils/data_handling.py
There is an issue when running `test_run_CreateMergeFile`. The output from different OS is different (probably due to rounding problems of numpy & co). To avoid this problem, numeric values from dataframes are rounded to 12 decimals when the tsv files are written by the function `create_merge_file`.
> Solve incompatibility issue for CreateMergeFile test

- docs/Pipelines/PET_Introduction.md
Hi,
There are some typos (maks, csf, bachground) on the Wiki.
Alex
> Fix typos in PET Introduction page

- clinica/utils/check_dependency.py
ANTs binaries should already be in PATH. No need for this extra check.
Closes #255
> Remove check for ANTSPATH

- clinica/iotools/converters/adni_to_bids/adni_utils.py
Raise explicit exception when creating clinical data and the image folders are not found.
> Raise exception on empty dataframe

- clinica/pipelines/deeplearning_prepare_data/deeplearning_prepare_data_pipeline.py
- clinica/pipelines/deeplearning_prepare_data/deeplearning_prepare_data_utils.py
The default values of some options have changed after the migration to Click. Consequently the checks in the code of the form option == None no longer worked. Updated the pipeline with consistent checks.
>  Fix DLPD checks after default values have changed by click introduction

- clinica/pipelines/cli_param/option.py
- clinica/pipelines/t1_volume_dartel2mni/t1_volume_dartel2mni_cli.py
- clinica/pipelines/t1_volume_existing_template/t1_volume_existing_template_cli.py
- clinica/pipelines/t1_volume_parcellation/t1_volume_parcellation_cli.py
- clinica/pipelines/t1_volume_parcellation/t1_volume_parcellation_pipeline.py
- docs/Pipelines/T1_Volume.md
The switch to Click changed the behavior of the `--modulate` flag which used to be set to true by default. This PR brings back the old behavior. Use `--no-modulate` to explicitly disable modulation.
Here is the corresponding output of the help string:
```sh
clinica run t1-volume -h
[...]
--modulate / --no-modulate    Modulate output images, no modulation preserves concentrations.  [default: modulate]
```
Closes #351
> Fix default value of modulate flag

- clinica/iotools/utils/data_handling.py
- clinica/iotools/utils/pipeline_handling.py
Values in the columns `first_column_index` and `last_column_index` in the summary file were false.
This commit fixes this bug.
> fix indices create-merge-tsv

- docs/Third-party.md
As mentioned in the upstream instructions in their [wiki](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#post-installation-set-environment-variables-path-and-antspath).
> Add missing trailing slash to ANTSPATH

- clinica/iotools/bids_utils.py
- clinica/iotools/converters/aibl_to_bids/aibl_to_bids_cli.py
- clinica/iotools/converters/aibl_to_bids/aibl_utils.py
- docs/Converters/ADNI2BIDS.md
- docs/Converters/AIBL2BIDS.md
- docs/Converters/NIFD2BIDS.md
- docs/Third-party.md
Remove the usage of FreeSurfer as a fallback for dcm2niix conversion in the `aibl-to-bids` converter.
To do:
> Enh bye freesurfer conv

- requirements.txt
- Avoid strict version pinning, which is not recommended
- A newer version of CMake is required for xgboost 1.x, which is not available in our MacOS CI
> Drop minimum version for xgboost

- clinica/iotools/converters/nifd_to_bids/nifd_utils.py
I just found out that preprocessed NIfTI files from NIFD are provided uncompressed. This PR ensures they end up compressed at install time.
> Compress preprocessed NIfTI files during install

- README.md
- docs/index.md
As discussed in our last group meeting, the plan is to freeze our Google group and transition to using GitHub discussions for handling support requests.
GitHub discussions is now stable, provides a better experience for writing support requests, and is not under threat of joining the evergrowing Google [graveyard](https://killedbygoogle.com/).
This PR invites users to first check past answers from Google group, but start new requests on GitHub discussions. This way both channels can still co-exist until we decide on a freeze date for the Google group.
> Promote GitHub discussions for new support requests

- clinica/iotools/converters/adni_to_bids/adni_utils.py
ADNI (like NIFD actually) seem to have slightly tweaked the file organization of the source data, which broke the image path finder for newer downloads (hello participant `002_S_1261`). LONI converters should no longer rely on parsing directory layouts and instead parse the image data filenames which are guaranteed (for now?) to contain the image data ID.
Closes #394
> Fix image path finder in ADNI converter

- test/nonregression/pipelines/test_run_pipelines_anat.py
- test/nonregression/pipelines/test_run_pipelines_dl.py
- test/nonregression/pipelines/test_run_pipelines_pet.py
`shared_folder_name` no longer exists
> Fix unexpected argument in non-regression tests

- clinica/iotools/converters/nifd_to_bids/nifd_utils.py
Also adds more accurate type signatures and prefer `None`over `pd.NA`for BIDS labels to simplify the code.
Closes #402
> Fix NIFD to BIDS conversion for MRI-only collections

- clinica/iotools/converters/nifd_to_bids/nifd_utils.py
DataFrame.from_records fails with a TypeError if the source iterator
yields no value instead of creating an empty dataframe. This change
replaces the useless empty dataframe check with an appropiate
try/catch block.
> NIFD: Fix error reporting when no imaging data found

- clinica/iotools/bids_utils.py
- clinica/iotools/converters/adni_to_bids/adni_to_bids.py
- clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py
- clinica/iotools/converters/adni_to_bids/adni_utils.py
Check each commit for contextual information about what is solved individually.
Closes #419
> More robust fetching of participants

- docs/Converters/ADNI2BIDS.md
Instructions for ADNI are missing a paragraph on how to process the archives downloaded from the LONI interface to obtain the clinical and imaging directories in the layout expected by the converter.
Closes #238
> Add instructions for clinical and imaging folder preparation

- clinica/iotools/converters/nifd_to_bids/nifd_utils.py
- clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py
Binary write mode was only introduced in Pandas version 1.2. Use text mode instead for compatibility with Python 3.6 (Pandas version 1.1.x).
> Open TSV files in text mode in NIFD and OASIS-3

- test/nonregression/pipelines/test_run_pipelines_stats.py
StatisticVolumeCorrection was not tested if the name is specified.
> Correct the name of the test so the same one is not tested twice

- clinica/pipelines/statistics_surface/statistics_surface_cli.py
- clinica/pipelines/statistics_surface/statistics_surface_utils.py
- test/nonregression/pipelines/test_run_pipelines_stats.py
the command line argument `covariate` was spelled without an `s` but used as `covariates` in the call to cli()
> Fix typo in StatisticsSurface cli

- test/instantiation/test_instantiate_all_pipelines.py
Folder name for instantiation test T1FreeSurfer has a wrong name (and the test fails if the OS is case sensitive).
> Change folder test name

- Jenkinsfile_nonregression
- test/nonregression/pipelines/test_run_pipelines_dwi.py
Non regression tests has a global timeout of 15h, 1 day over 2, starting at 9pm (CET). All the tests runs on the same agent.
> Change architecture for non regression tests

- clinica/cmdline.py
Nipype's logging can become quite verbose and is only relevant under
abnormal circumstances. Moving its output to a separate file clears the
Clinica console output from unwanted nipype information regardless of
the desired verbosity, whilst providing the necessary debug information
for support requests.
This commit isolates Nipype's logging from Clinica's. Nipype now works
in debug mode and logs its output to a file instead of the console
previously. The verbosity option for Clinica has also been simplified to
two values (INFO and DEBUG) with INFO kept as default.
Closes #363
> Split Clinica and Nipype logging

- Jenkinsfile_nonregression
Trigger scheduled test only on weekends and deactivate PET (non-regression) tests for mac.
> Fix schedule for non-regression tests only on weekends

- clinica/iotools/utils/data_handling.py
Following [Issue 478](https://github.com/aramis-lab/clinica/issues/478), `merge-tsv` is not currently robust to duplicate columns in the tsv files. 
A quick fix is to drop duplicates if found. Open to other suggestions.
> Remove duplicate columns if found

- clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_pipeline.py
- clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_pipeline.py
- clinica/pipelines/machine_learning/input.py
- clinica/pipelines/machine_learning_spatial_svm/spatial_svm_pipeline.py
- clinica/pipelines/pet_linear/pet_linear_pipeline.py
- clinica/pipelines/pet_surface/pet_surface_pipeline.py
- clinica/pipelines/pet_volume/pet_volume_pipeline.py
- clinica/pipelines/statistics_volume/statistics_volume_pipeline.py
- clinica/pipelines/t1_freesurfer/t1_freesurfer_pipeline.py
- clinica/pipelines/t1_freesurfer_atlas/t1_freeesurfer_atlas_pipeline.py
- clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_template_pipeline.py
- clinica/pipelines/t1_linear/t1_linear_pipeline.py
- clinica/pipelines/t1_volume_create_dartel/t1_volume_create_dartel_pipeline.py
- clinica/pipelines/t1_volume_dartel2mni/t1_volume_dartel2mni_pipeline.py
- clinica/pipelines/t1_volume_parcellation/t1_volume_parcellation_pipeline.py
- clinica/pipelines/t1_volume_register_dartel/t1_volume_register_dartel_pipeline.py
- clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py
- clinica/utils/inputs.py
Clinica's file reader current version doesn't allow to visualize missing files (*T1w.nii.gz) and to run the pipeline at the same time.
To enable this and give more flexibility, we return the error message containing the missing files and the results together. the message will be empty if no files are missing.
> Enable FreeSurfer to run with missing files

- Jenkinsfile
Happens in builds not triggered by a PR, like after a merge on `dev`.
> Use branch name as fallback when change ID is not defined

- clinica/iotools/bids_utils.py
- clinica/iotools/converters/adni_to_bids/adni_utils.py
- clinica/iotools/converters/aibl_to_bids/aibl_utils.py
- clinica/iotools/converters/nifd_to_bids/nifd_utils.py
All calls to dcm2niix now transit through the `run_dcm2niix` helper
function. Do not use shell=True to allow proper escaping of white
spacing in path arguments.
Closes #527
> Normalize subprocess calls to dcm2niix

- mkdocs.yml
- poetry.lock
- pyproject.toml
This PR fixes recent warnings about the deprecation of the current google analytics settings.
`WARNING  -  Config value: 'google_analytics'. Warning: The configuration option google_analytics has been deprecated and will be removed in a future release of MkDocs. See the options available on your theme for an alternative.`
See: https://github.com/squidfunk/mkdocs-material/issues/2055
> Update google analytics configuration

- clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py
Whilst trying to reproduce #478, I had to perform a BIDS conversion for OASIS-1. This PR makes conversion a bit more flexible w.r.t. the imaging dataset layout, which improves the user experience.
The user had to untar each archive and fuse the content of each directory (`disc1` to `disc12`) to a common location manually.
Just point the converter to the directory where all `discX` folders have been extracted. No more fusing required. The old behavior (a single fused directory) still works.
> Support more flexible dataset layouts for OASIS-1

- .github/workflows/stale.yaml
Issues are automatically labelled `stale` after 14 days of inactivity.
Issues are automatically closed after further 14 days of inactivity.
See: https://github.com/actions/stale
> Automate management of stale issues

- clinica/cmdline.py
This feature leads to unnecessary spamming in the debug logs.
See: https://github.com/nipy/nipype/blob/master/nipype/utils/config.py#L64
> Do not let nipype check for updates

- clinica/iotools/converters/adni_to_bids/adni_utils.py
When the number of folders in `conversion_info` exceeded 9, the `adni-to-bids` converter was sorting the subfolders wrong (because of the way strings such as `v10` are sorted before `v9`). This would lead to inconsistent states and potential crashes. This PR fixes this issue.
> Sort conversion_version folders when above 9

- clinica/iotools/converters/adni_to_bids/adni_utils.py
Some unwanted `session_id` values were copied from ADNI's metadata. This fix tighten the check on the format of the `session_id`
> Tighten the check on the session id values

- Jenkinsfile_nonregression
DWI tests currently fail on weekly non regression tests, preventing other tests from completing. This PR disables these tests until a fix has been found.
> Disable DWI tests waiting for fix

- clinica/pipelines/t1_freesurfer/t1_freesurfer_pipeline.py
- clinica/utils/inputs.py
When clinica_file_reader is called, if the inputs and outputs are the same (meaning the inputs have already been processed),  the function will exit early with a return.  One output of this return was missing.
> Add a forgotten output to clinica_file_reader

- clinica/iotools/bids_dataset_description.py
- clinica/iotools/converters/aibl_to_bids/aibl_to_bids.py
- clinica/iotools/converters/habs_to_bids/habs_to_bids.py
- clinica/iotools/converters/nifd_to_bids/nifd_utils.py
- clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py
- clinica/iotools/utils/data_handling.py
- clinica/iotools/utils/pipeline_handling.py
- clinica/pipelines/dwi_dti/dwi_dti_utils.py
- clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_utils.py
- clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_utils.py
- clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_workflows.py
- clinica/pipelines/pet_surface/pet_surface_utils.py
- clinica/pipelines/pet_volume/pet_volume_utils.py
- clinica/pipelines/t1_freesurfer_longitudinal/longitudinal_utils.py
- clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_longitudinal_correction_pipeline.py
- clinica/utils/atlas.py
- clinica/utils/filemanip.py
- clinica/utils/input_files.py
- clinica/utils/ux.py
The current state of the code does not lint without errors, meaning code style drifted from the expected config.
This PR runs a project-wide format to normalize the formatting back to a state where it lints without errors.
> Run project-wide format before release

- Makefile
This Makefile provides a unified set of commands to perform basic
project operations such as formatting, linting, generating the docs or
publishing the package to pypi or testpypi.
Instead of remembering specific `mkdocs` or `poetry` commands with their
corresponding arguments, contributors may just type the appropriate make
command, such as:
```console
$ make doc
$ make format
$ make lint
$ make publish
```
> Add Makefile to facilitate project operations

- clinica/pipelines/pet_linear/pet_linear_pipeline.py
[PR#524](https://github.com/aramis-lab/clinica/pull/524) changed the return type of `clinica_file_reader()` but did not update the a call of this function in `pet-linear` this caused the pipeline to run indefinitely. This PR fixes this issue.
> Update call to clinica_file_reader with new signature

- mkdocs.yml
The CNIL just ruled Goggle Analytics as breaking GDPR.
https://www.cnil.fr/fr/utilisation-de-google-analytics-et-transferts-de-donnees-vers-les-etats-unis-la-cnil-met-en-demeure
> Remove GA from docs

- poetry.lock
- pyproject.toml
Used by the Similarity measure in nipype, which we use in part of our
testing.
> Add nipy to dev dependencies

- clinica/iotools/bids_utils.py
- clinica/iotools/utils/data_handling.py
The Pandas Dataframe `append` method is [deprecated since 1.4.0](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.append.html#pandas.DataFrame.append).
This PR proposes to remove the deprecation warnings in a couple places in `iotools` by using the recommended `pd.concat` instead.
> [MAINT] Remove deprecated pandas append method in ìotools`

- clinica/iotools/converters/aibl_to_bids/aibl_utils.py
Found this while fixing warnings in AIBL writer. `replace` does not work inplace by default so it was not doing anything.
Before:
```
sub-AIBL1607	1607	1943	M	1	-4	-4
sub-AIBL1608	1608	1935	M	1	4	3
sub-AIBL1609	1609	1947	F	1	-4	-4
sub-AIBL1610	1610	1932	M	2	4	3
sub-AIBL1611	1611	1940	F	2	-4	-4
sub-AIBL1613	1613	1939	M	2	3	3
sub-AIBL1614	1614	1940	M	1	-4	-4
sub-AIBL1615	1615	1932	M	1	3	3
sub-AIBL1616	1616	1937	F	1	4	3
sub-AIBL1618	1618	1947	M	1	3	3
```
After:
```
sub-AIBL1607	1607	1943	M	1	n/a	n/a
sub-AIBL1608	1608	1935	M	1	4	3
sub-AIBL1609	1609	1947	F	1	n/a	n/a
sub-AIBL1610	1610	1932	M	2	4	3
sub-AIBL1611	1611	1940	F	2	n/a	n/a
sub-AIBL1613	1613	1939	M	2	3	3
sub-AIBL1614	1614	1940	M	1	n/a	n/a
sub-AIBL1615	1615	1932	M	1	3	3
sub-AIBL1616	1616	1937	F	1	4	3
sub-AIBL1618	1618	1947	M	1	3	3
```
> Fix NA value normalization in AIBL writer

- clinica/iotools/converters/aibl_to_bids/aibl_utils.py
ParserWarning: Falling back to the 'python' engine because the 'c'
engine does not support regex separators (separators > 1 char and
different from '\s+' are interpreted as regex); you can avoid this
warning by specifying engine='python'.
> Fix parser warning in AIBL reader

- clinica/iotools/converters/aibl_to_bids/aibl_utils.py
Instead of normalizing the participant's dataframe inplace row per row,
perform data transformations column by column. This is both more
effective and makes this warning disappear.
> Fix Pandas warning in AIBL writer

- clinica/pipelines/pet_surface/pet_surface_pipeline.py
This PR makes the `pet-surface` pipeline write to its reserved folder (like other PET pipelines do), instead of the root working directory directly.
> Fix working directory for pet-surface

- clinica/iotools/converters/habs_to_bids/habs_to_bids.py
Before:
```
ref/
├── dataset_description.json
├── participants.tsv
└── sub-HABS1NIBUB
├── ses-M00
│   ├── anat
│   │   ├── sub-HABS1NIBUB_ses-M00_FLAIR.nii.gz
│   │   └── sub-HABS1NIBUB_ses-M00_T1w.nii.gz
│   ├── pet
│   │   └── sub-HABS1NIBUB_ses-M00_trc-11CPIB_pet.nii.gz
│   └── scans.tsv
├── ses-M36
│   ├── anat
│   │   ├── sub-HABS1NIBUB_ses-M36_FLAIR.nii.gz
│   │   └── sub-HABS1NIBUB_ses-M36_T1w.nii.gz
│   ├── pet
│   │   └── sub-HABS1NIBUB_ses-M36_trc-11CPIB_pet.nii.gz
│   └── scans.tsv
├── ses-M60
│   ├── anat
│   │   ├── sub-HABS1NIBUB_ses-M60_FLAIR.nii.gz
│   │   └── sub-HABS1NIBUB_ses-M60_T1w.nii.gz
│   ├── pet
│   │   └── sub-HABS1NIBUB_ses-M60_trc-11CPIB_pet.nii.gz
│   └── scans.tsv
└── sub-HABS1NIBUB_sessions.tsv
```
After:
```
ref/
├── dataset_description.json
├── …
```
> Add missing source entities to scans file in HABS converter

- Jenkinsfile_nonregression
CI data were updated and DWI tests can now normally run well. MacOS tests were not yet un-commented as it is yet left to decide what do do about ML tests not succeeding.
> Uncomment DWI non regression tests for linux

- clinica/iotools/utils/data_handling.py
- test/nonregression/iotools/test_run_utils.py
- test/nonregression/testing_tools.py
Entity parsing in some iotools rely on positional location of tokens, which is very fragile. This PR adjusts the location to the new standards adopted for PET, but a long term solution should be to resort to entity prefix parsing instead.
Requires synchronization of data for CI to pass.
> Fix PET entity parsing in iotools

- clinica/iotools/converters/habs_to_bids/habs_to_bids.py
Some more compliance related fixes for HABS:
- Only store `age` attribute at the session level
Instead of both at the participant and session levels, which is not compliant with BIDS inheritance principle.
- Column names in tabular data all lowercase
This is a recommandation from the BIDS specification to store tabular columns in `snake_case`.
- Use `years_of_education` instead of `education`
Improves interpretation of this specific metadata attribute.
> Fix BIDS compliance of HABS converter

- Jenkinsfile_nonregression
The non-regression tests fails because of a environment set-up problem in macos. Last run of scheduled tests failed to finish on linux as well. This PR comments out all the tests on macos temporarily to pinpoint the issue.
> Disable macos non-regression tests in Jenkinsfile_nonregression

- test/nonregression/testing_tools.py
Quick fix for non-regression tests to skip empty directories when comparing
> Skip empty dirs in compare_folders()

- clinica/pipelines/t1_linear/t1_linear_pipeline.py
- clinica/pipelines/t1_linear/t1_linear_utils.py
This PR removes superflous node connections and substitutions from a past behaviour where the output of the intermediate bias field corrected image used to be saved as an output of the workflow. Now that this is no longer the case (not even with a parameter), it is worth getting rid of the dead code which only adds confusion to the process of transitionning the output of T1Linear to a BIDS compliant format.
> Remove superfluous code in T1Linear pipeline

- clinica/iotools/converters/adni_to_bids/adni_utils.py
Mapping from visit code to session ID may not be exhaustive enough, or invalid
visit codes may be present. In this case, null session IDs are produced and can
cause failures downstream. Filtering rows containing those invalid session IDs
provides safer guarantees to the rest of the processing.
Closes #632
> Filter rows with invalid session IDs in ADNI converter

- test/unittests/iotools/test_bids_utils.py
After changes in UKB to `.bidsignore` the unittest failed on `test_write_modality_agnostic_files`. This PR updates the test with `swi/` that was added to `.bidsignore` writer.
> Update unitest with swi folder in bidsignore

- clinica/pipelines/pet_surface/pet_surface_utils.py
- clinica/pipelines/statistics_volume/statistics_volume_pipeline.py
- clinica/pipelines/t1_volume_create_dartel/t1_volume_create_dartel_pipeline.py
- clinica/pipelines/t1_volume_dartel2mni/t1_volume_dartel2mni_pipeline.py
- clinica/pipelines/t1_volume_register_dartel/t1_volume_register_dartel_pipeline.py
- clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py
This PR retires our old wrapper function for decompressing nifti files and uses the `Gunzip` interface directly instead. It remains functionally equivalent, since the wrapper function was essentially calling this interface underneath.
As far as compression is concerned, I filed this [issue](https://github.com/nipy/nipype/issues/3471) upstream to collect opinions on whether it would make sense to extend this interface to produce compressed nifti files. I believe it would.
> Use Gunzip interface directly

- Makefile
`make format | lint` may output nothing if the code is fine.
This PR prints a confirmation that those tools have been run.
> ENH: Warn when formatting or linting for each tool

- clinica/pipelines/pet_volume/pet_volume_pipeline.py
- clinica/utils/filemanip.py
Follow-up of #650, with one last replacement in the `pet-volume` pipeline.
Also drops the now defunct `unzip_nii` utility function.
As far as `zip_nii` is concerned, we'll have to wait for the next release of `nipype` where I have contributed a [Gzip interface](https://github.com/nipy/nipype/pull/3472) for compression.
> ENH: Replace unzip_nii utility with Gunzip interface

- docs/IO.md
Add a note on the "_intensity" suffix for merge tsv in the documentation.
> Add note concerning the _intensity suffix in merge tsv volume outputs

- .pre-commit-config.yaml
- clinica/utils/inputs.py
Hello :)
I am currently using the `extract` function of ClinicaDL which relies on `clinica_file_reader`, and on a large data set this takes forever.
This is why I propose to parallelize the `clinica_file_reader` with `joblib`.
I also changed the version of black used for the environment installation of pre-commit as I encountered the same error as in https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click (now it works).
Tell me if you need more explanations or if you think this should be done differently.
Best,
> Parallel file reader

- clinica/pipelines/machine_learning/input.py
- clinica/pipelines/machine_learning/region_based_io.py
- clinica/pipelines/machine_learning/tsv_based_io.py
- clinica/utils/filemanip.py
- clinica/utils/participant.py
- clinica/utils/pet.py
Using `pd.io.parsers` triggers a `Cannot find reference` warning from code introspection in PyCharm. Anyway, the officially documented import for `read_csv` is the top-level `pandas` module, so we should normalize our code base to it.
> Call read_csv from the top-level pandas module

- clinica/iotools/converter_utils.py
`mod_list` can be `None` or `[]`, using `False` leads to a type mismatch warning.
> Fix default value in MissingModsTracker constructor

- clinica/iotools/converters/adni_to_bids/adni_utils.py
Found that one whilst dealing with #670.
It still worked because the preceding `os.listdir` operation seem to return a sorted iterable. This PR ensures sorting does happen no matter what `os.listdir` returns.
> Fix accidental bypass of sorting the conversion versions

- .github/workflows/test_install.yml
After reviewing #677 I thought it'd be great to test basic install on all supported platforms and python versions in order to spot these dependency issues early on.
This PR investigates the use of a GitHub action to do that.
Note: I will remove the trigger on pull requests once this is working and only test on push to the dev branch.
> [INFRA] Test basic install on all supported Python versions

- .github/workflows/codeql-analysis.yml
Version 1 is deprecated, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1
> Upgrade CodeQL Action to version 2

- .github/workflows/test.yml
- clinica/__init__.py
- Use `snok/install-poetry` GH action to deploy Poetry configured with inplace venv support.
- Cache the venv created by Poetry by product of OS, Python version and hash of the lock file.
- Cache miss happens if the Python version changes or the lock file is updated.
> ci: Add caching support for unit tests

- clinica/pipelines/pet_surface/pet_surface_utils.py
- clinica/pipelines/pet_volume/pet_volume_pipeline.py
- clinica/pipelines/statistics_volume/statistics_volume_pipeline.py
- clinica/pipelines/t1_volume_create_dartel/t1_volume_create_dartel_pipeline.py
- clinica/pipelines/t1_volume_dartel2mni/t1_volume_dartel2mni_pipeline.py
- clinica/pipelines/t1_volume_register_dartel/t1_volume_register_dartel_pipeline.py
- clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py
- clinica/utils/filemanip.py
As mentioned in Issue #707 , `t1-volume` currently hangs because of a a regression introduced in PR #650 (handling of lists as inputs). This PR reverts that PR and #656 which was a followup. If time allows, we can introduce `Gunzip` again by accounting lists as inputs as well.
> Revert gunzip use

- docs/Pipelines/T1_Volume.md
Hi Clinica :)
I am currently launching `t1-volume` and I am always confused by the notations in the doc between `group_label` and `group_id` (where `group_id` = `group-<group_label>` but it is not written anywhere).
Here is a small PR to homogeneize.
> Homogeneize notations

- test/nonregression/pipelines/test_run_pipelines_dwi.py
- test/nonregression/pipelines/test_run_pipelines_ml.py
- test/nonregression/pipelines/test_run_pipelines_pet.py
- test/nonregression/pipelines/test_run_pipelines_stats.py
This PR fixes a regression introduced in #694 by importing `Path` into the non-regression modules.
> Add import pathlib to nonregression tests

- test/nonregression/pipelines/test_run_pipelines_anat.py
Fixes the T1Linear non-regression test by specifying a name to the pipeline and avoiding the default. The name became mandatory after introducing Flair Linear.
> Add name to T1Linear test

- clinica/iotools/utils/data_handling.py
Drops empty line in dataframe when using create_subs_sess_list() to avoid `nan` and `str` concatenation error.
> Handle empty lines in create_subs_sess_list

- clinica/iotools/utils/data_handling.py
- clinica/iotools/utils/pipeline_handling.py
`merge-tsv` raises a lot of warning from pandas which prevents other messages from being seen.
This PR solves these issues.
> Fix warnings in `merge-tsv`

- clinica/pydra/engine.py
- clinica/pydra/t1_linear/t1_linear.py
- clinica/pydra/t1_linear/t1_linear_cli.py
- clinica/pydra/t1_volume/tissue_segmentation/pipeline.py
- test/unittests/pydra/test_engine.py
After discussion with @NicolasGensollen, it seems easier to handle the splits and combines directly inside the core workflows instead of the readers. This PR proposes to update the engine to reflect this proposal.
> Enh remove split from engine

- clinica/iotools/utils/data_handling.py
As pointed out in #743, `t1-volume` doesn't work with data from `OASIS-3`. It seems that the function `vox_to_world_space_method_1()` was missing some brackets (which are present in vox_to_world_space_method_2 and 3).
Closes #743.
> Fix vox_to_world_space_method_1

- .github/workflows/lint.yaml
- .github/workflows/test.yml
- Makefile
Recent versions of [actions/setup-python](https://github.com/actions/setup-python/releases/tag/v3.1.0) now support caching `poetry` dependencies.
This PR makes use of this new caching feature which enables further simplification of our CI scripts and make targets and removal of our custom cache management step.
> Use cache feature of actions/setup-python@v4

- .github/workflows/lint.yaml
- .github/workflows/stale.yaml
- .github/workflows/test.yml
As part of the recommended [security hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions) guidelines for GH workflows.
Whenever a checkout occurs:
```yaml
permissions:
contents: read
```
Stale workflow may edit issues and PRs, so need:
```yaml
permissions:
issues: write
pull-requests: write
```
> Restrict GH permissions to minimum necessary

- poetry.lock
- pyproject.toml
Version 1.8.3 introduced a regression to the DWI bias correction interface.
See https://github.com/nipy/nipype/pull/3523
> build: Install nipype up to version 1.8.2

- poetry.lock
- pyproject.toml
Force using joblib >= 1.2.0 as a security issue was recently fixed.
See https://github.com/joblib/joblib/pull/1321 and https://github.com/joblib/joblib/pull/1327
> [MAINT] Upgrade joblib to `1.2.0`

- clinica/pydra/engine.py
- clinica/pydra/engine_utils.py
- clinica/pydra/t1_linear/t1_linear.py
- clinica/pydra/t1_volume/tissue_segmentation/pipeline.py
- poetry.lock
- pyproject.toml
- test/unittests/pydra/test_engine.py
This PR proposes to refactor the BIDS (see #658) and CAPS (see #731) reader configurations. More precisely, this PR attempts to:
- propose a uniform format for BIDS and CAPS queries which used to be specified as strings and dictionaries respectively. Now, everything is specified as dictionaries.
- factorize the code since both readers now expect similar data formats
Another reason, which originally motivated this refactoring is that we will pretty soon have to provide more complex BIDS input specifications than simple strings (as it is currently the case for `t1-linear` with `T1W`). 
For example, in `PETVolume` (see #729), we need to read PET scans as inputs, but the user specifies through the CLI the tracer of interest. This means that we need to be able to dynamically pass this …
> [REF] Refactor BIDS and CAPS reader configurations

- poetry.lock
- pyproject.toml
Now that VTK 9.2 is officially released in PyPI as stable, we can clear the project file from this temporary hack and let Poetry fetch the right version transitively.
> [CI] Drop explicit dependencies on BrainSpace and VTK

- Makefile
- poetry.lock
Subpart of #763 which is compatible with Poetry version 1.1.x.
> [BUILD] Add target to refresh locked dependencies

- clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_pipeline.py
DWIPreprocessingUsingT1 crashes following changes made in nipype as detailled in this PR [#3523](https://github.com/nipy/nipype/pull/3523).
After testing, giving the `out_file` to the DWIBiasCorrect interfaces enables the pipeline not to crash.
> Add out_file parameter to DWIBiasCorrect

- clinica/iotools/utils/data_handling.py
- test/nonregression/iotools/test_run_utils.py
- Fixes centering bypassed entirely if no modality specified (#779)
- Add typing annotations to `center_all_nifti`
- Rewrite docstring in numpydoc style
Closes #779
> Center all modalities if no modality is specified

- clinica/cmdline.py
- docs/InteractingWithClinica.md
Defaults to current working directory, unless CLINICA_LOGGING_DIR is set. This is a stop gap solution for #771 until a proper config structure for customising Clinica is designed.
Closes #771 
Closes #772
> Allow setting a custom logging directory via an envvar

- clinica/iotools/converters/ukb_to_bids/ukb_utils.py
- test/unittests/iotools/converters/ukb_to_bids/test_ukb_to_bids_utils.py
Currently, ukb-to-bids converter errors in not so user friendly way if the imaging data is not found or if it is filtered (since we do not convert all of the modalities).
Closes #783.
> [UKB-To-BIDS] Add error if the data is not found or filtered

- .github/workflows/publish.yaml
- Makefile
This PR updates the Makefile targets to enable publishing to PyPI if a valid API token is passed throught the `PYPI_TOKEN` envvar. It also adds a new workflow dedicated to publishing, which is triggered when a GitHub release is successfully drafted. It requires a repository secret to be set with the name `PYPI_TOKEN`, which can be done subsequently after this PR is merged.
> [CI] Automate publishing to PyPI on new releases

- clinica/utils/filemanip.py
- test/unittests/utils/test_filemanip.py
This PR proposes to improve the `clinica.utils.filemanip` module by:
- Adding type hints when possible
- Adding docstrings following the Numpydoc's conventions
- Refactoring some code
- Adding unit tests for all functions
Also, the function `unzip_nii` was implemented in a very different way from `zip_nii` and was offering a different API. This PR also proposes to change this and have the same implementation and API for both functions.
> [TEST, DOC] Add tests and docstrings to functions from `filemanip.py`

- clinica/pydra/engine_utils.py
- clinica/pydra/interfaces.py
- clinica/pydra/query.py
- poetry.lock
- pyproject.toml
- test/unittests/pydra/test_engine.py
- test/unittests/pydra/test_interfaces.py
- test/unittests/pydra/test_query.py
Required dropping `datatype` for BIDS reader queries, as they are not supported by `ancpbids` which is used by `pydra-bids` under the hood. It's not a big deal since the suffix is enough to select the desired modality for the files.
Closes #722 
Closes #73
> Read BIDS datasets using pydra-bids tasks

- .github/workflows/publish.yaml
A release can be drafted but not published. This setting ensures upload happens only when the release is published.
> [CI] Upload package when a release is published

- clinica/iotools/converters/aibl_to_bids/aibl_utils.py
- test/unittests/iotools/converters/aibl_to_bids/test_aibl_utils.py
Found when trying to reproduce #786 with a local AIBL dataset containing a collection and associated XML metadata.
Without this fix, the converter fails with the following error:
```
ValueError: invalid literal for int() with base 10: 'AIBL_1262_PET-CTAC_SUM_S236830_I453888.xml'
```
Resulting from the fact that the `listdir_nohidden` utility function will return first-level directories **and files**, unlike what its name and docstring suggest 🤦 
There is a lot of horrible code in this converter so I went for the immediate fix, which is to replace the implementation with one based on `pathlib` and use `Path.is_dir` to filter first-level files from what's being returned. I also took this opportunity to update the docstring and add tests.
> FIX: Only list first-level non-hidden directories

- clinica/iotools/bids_utils.py
Currently the conditions for a row to be be extracted from the csv's are wrong, since the condition is always false and therefore no metadata are ever extracted.
> Fix create_scan_dict's row_to_extract conditions

- .editorconfig
Helps mantaining a consistent codestyle (at least the basics) for most IDEs.
Since I know we all use different IDEs in the team, this should help reduce inconsistencies. All IDEs support most, if not all EditorConfig [properties](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties) these days. Properties are collected and overriden top-down.
> MNT: Add EditorConfig file

- clinica/pipelines/__init__.py
- clinica/pydra/__init__.py
- clinica/pydra/pet_volume/__init__.py
- clinica/pydra/pet_volume/pet_volume_cli.py
- clinica/pydra/t1_linear/__init__.py
- clinica/pydra/t1_volume/__init__.py
- clinica/pydra/t1_volume/create_dartel/__init__.py
- clinica/pydra/t1_volume/create_dartel/cli.py
- clinica/pydra/t1_volume/register_dartel/__init__.py
- clinica/pydra/t1_volume/tissue_segmentation/__init__.py
- clinica/pydra/t1_volume/tissue_segmentation/cli.py
- test/instantiation/test_cli.py
Fixes the following warning:
`RuntimeWarning: The empty option group "Common pipelines options" was found (line 56) for "cli". The group will not be added.`
Also add  instantiation tests for all Pydra pipelines (they are hidden but they can still be tested).
> FIX: Test instantiation for all Pydra pipelines

- clinica/iotools/converters/habs_to_bids/habs_to_bids.py
- clinica/iotools/converters/nifd_to_bids/nifd_utils.py
- clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py
Atm, each converter defines its own copy of the function `write_to_tsv`:
https://github.com/aramis-lab/clinica/blob/83d6d9958b3b3e2ffe82e5fedf09cd70b3109a44/clinica/iotools/converters/habs_to_bids/habs_to_bids.py#L173-L175
https://github.com/aramis-lab/clinica/blob/444e4a4e711d6a373fae07412fa378da1e356572/clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py#L263-L265
https://github.com/aramis-lab/clinica/blob/83d6d9958b3b3e2ffe82e5fedf09cd70b3109a44/clinica/iotools/converters/nifd_to_bids/nifd_utils.py#L289-L291
This PR proposes to delete these duplicated functions and import the implementation of the `bids_utils` module:
https://github.com/aramis-lab/clinica/blob/83d6d9958b3b3e2ffe82e5fedf09cd70b3109a44/clinica/iotools/bids_utils.py#L780-L782
> [ENH] Delete duplicated function `write_to_tsv`

- .jenkins/doc_build
Just realized it when iterating on #838
> CI: Fix typos in user docs failure email

- clinica/iotools/converters/ukb_to_bids/ukb_utils.py
Fix warning `FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only.` reported in CI with the latest version of `pandas`. The `axis` parameter will become keyword-only and we are using the default value anyway. Better just remove it.
> FIX: FutureWarning in pandas.concat

- clinica/iotools/converters/ukb_to_bids/ukb_utils.py
The current implentation takes as input the `T2_FLAIR.nii.gz`. This image is registered on the T1 image and it is therefore not the one we wish to convert to BIDS, as it is not the rawest image, which would be `T2_FLAIR_orig_defaced.nii.gz`.
> [UKB2BIDS] Correct the file that is used for FLAIR

- .jenkins/nonregression_fast.Jenkinsfile
I realized I missed a configuration on Jenkins and the daily pipeline wasn't triggered.
This PR just changes the time from 4pm et 6pm such that we get another shot at it today.
> [CI] Update cron nonregression tests fast

- test/nonregression/pipelines/test_run_pipelines_anat.py
Fix bug introduced in #810 which is causing the anat non regression tests to fail atm.
> [FIX] Fix wrong 4 digits session number in non regression test

- clinica/pipelines/statistics_volume/statistics_volume_pipeline.py
- clinica/pipelines/t1_volume_parcellation/t1_volume_parcellation_cli.py
- clinica/pipelines/t1_volume_parcellation/t1_volume_parcellation_pipeline.py
- clinica/utils/input_files.py
Fixes #830 
This PR proposes a possible fix for #830 by adding a new `fwhm` argument to `t1_volume_template_tpm_in_mni` in order to query files obtained with smoothing, similar to what is done for pet.
@AudreyDuran I still need to test it but feel free to take a look and check if this patch fixes your problem.
> [FIX] Expose `fwhm` to `t1_volume_template_tpm_in_mni`

- .jenkins/nonregression_fast.Jenkinsfile
- .jenkins/nonregression_slow.Jenkinsfile
This PR fixes the `poetry not found` errors we are currently getting when running non regression tests on Mac OS machines. We already fixed this a couple weeks ago on Linux machines but because the Jenkins files are full of copy pasted stuffs, we missed the Mac OS configs. I believe this is another example of why using shared libs as proposed by @ghisvail would save us time (see PR #841).
> [CI] Fix poetry not found on MacOS machines

- .jenkins/Jenkinsfile
- .jenkins/nonregression_fast.Jenkinsfile
- .jenkins/nonregression_slow.Jenkinsfile
Fix the current issue we have with non regression test pipelines running on MACOS machines.
The pipelines fail at the node `PETnonreg` because the associated script attempts to source a non-existing file which probably comes from a copy-paste from the same node defined for Linux machines. 
Once again, a good reason to move to shared libs (see #841).
> [CI] Fix modules on macOS machines

- test/nonregression/pipelines/test_run_pipelines_pet.py
`PETSurfaceCrossSectional` is not a valid folder name in the CI data. This is causing the weekly non regression tests to fail atm.
> [TEST] Fix test pet surface

- test/nonregression/pipelines/test_run_pipelines_dwi.py
Fix two small bugs in non regression tests for DWI:
- wrong test function called, bug introduced in #837 
- two digit session instead of three, bug introduced in #810
> [FIX] Fix non regression tests DWI

- test/instantiation/test_instantiate_all_pipelines.py
Closes #859 
Alternative possible solution for the intermittent errors we currently have in instantiation tests. The error happens when running tests in parallel, for pipelines relying on SPM.
After investigation, I'm still unsure why this happens and why it seems to happen more frequently on `clinica-ubuntu-3`... I tried with SPM standalone and without and I get the same results.
In #859, I was proposing to run the instantiation tests in a single process to avoid these failures.
This PR proposes instead to keep the parallelism at the pytest session level, but group the tests using SPM in a single test function. 
It also proposes to clean the names of the test functions (remove all capital letters which are not PEP8 compliant), and explicitly skip a test which was commented (I don't know …
> [CI, TEST] Run SPM instantiation tests in same process

- .jenkins/nonregression_fast.Jenkinsfile
- Remove the DWI non regression "fast" tests stage since there aren't any atm
- Remove the `catchError` for stages of the linux pipeline in order to be consistent with the MACOS pipeline. Atm most stages of the linux pipeline get tagged as unstable for some reason. Now that we've increased the execution frequency of these tests, I'd prefer them to fail fast with a clear error message if they should fail.
> [CI] Remove catch error and DWI non regression fast

- .github/workflows/test.yml
- poetry.lock
- pyproject.toml
Requires wheels for `h5py`, see https://github.com/h5py/h5py/issues/2146
~~I thought VTK would be the only obstacle, I was wrong.~~
We now have wheels for Python 3.11.
> MNT: Enable install and testing for Python 3.11

- README.md
- environment.yml
- Promote pipx as the recommended method for install
- Promote conda as means to install Clinica plus dependencies
- Explain why all third-party dependencies cannot be distributed
- Use Python 3.10 for the conda environment (now the default version)
> DOC: Improve getting started section of the readme

- clinica/pipelines/engine.py
- clinica/utils/check_dependency.py
- test/unittests/utils/test_check_dependency.py
This PR proposes to make a few changes to `clinica/utils/check_dependency.py`:
- Add type hints to functions
- Update existing docstrings to follow Numpydoc conventions
- Add documentations and examples
- Refactor check functions to be partials and not duplicate the checking logic
- Add unit tests
- Remove `check_software_requirements` which was not used
> [REF TEST] Refactor and add unit tests for `check_dependency`

- clinica/iotools/converter_utils.py
- clinica/iotools/utils/data_handling.py
- test/unittests/iotools/test_converter_utils.py
This PR proposes to update the utilities defined in `clinica.iotools.converter_utils.py`:
- Add type hints to functions
- Update existing docstrings to follow Numpydoc conventions
- Add documentations
- Refactor the `MissingModsTracker` class
- Simplify constructor
- Add safety checks in associated methods
- Refactor `print_statistics`, `print_longitudinal_analysis`, and `print_table`
- Decouples the summary string generation logic from the file writing.
- Rename to `write_*` since they write to files and don't print
- Pass `Path` objects instead of file handles which avoids forgetting to close them
- Remove `has_one_index` which was not used
- Remove `increment_dict` and use a `Counter` object instead
- Add unit tests
> [REF TEST] Refactor `converter_utils`

- .github/workflows/publish.yaml
- Makefile
Use the official [build](https://pypa-build.readthedocs.io/) and [publish GHA](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) from the PyPA to release Clinica to PyPI.
> CI: Improve publish workflow

- .jenkins/nonregression_fast.Jenkinsfile
- test/nonregression/pipelines/test_run_pipelines_dwi.py
This PR proposes to add non regression tests specific to the `b0_flirt` pipeline which relies on FSL to perform rigid registration of the B0 dataset onto the first DWI volume.
The pipeline is defined here:
https://github.com/aramis-lab/clinica/blob/0566ca64de22e5c9ec522cdb0268c1c04538c2c7/clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_workflows.py#L334-L338
and used in the `DWIPreprocessingUsingT1` pipeline:
https://github.com/aramis-lab/clinica/blob/5733d8c1c5817fa8dcff5b4ce38b4c06802f20b6/clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_utils.py#L284-L287
The test is relatively fast and runs in a few minutes (usually 3 to 4 minutes).
This PR is linked to the data PR: https://github.com/aramis-lab/clinica_data_ci/pull/24
> [TEST] Add non regression test for B0 flirt pipeline

- clinica/pipelines/dwi_dti/dwi_dti_pipeline.py
- clinica/pipelines/dwi_dti/dwi_dti_utils.py
- clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_utils.py
- clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_utils.py
- clinica/utils/dwi.py
- test/unittests/utils/test_dwi.py
The `DWIDTI`, `DWIPreprocessingUsingT1`, and `DWIPreprocesingUsingPhasediff` pipelines all have a function `rename_into_caps` which instantiates iteratively as many `Rename` nodes as files to rename.
This PR proposes to do some refactoring such that:
- A loop is used to avoid code duplication
- The logic is moved to a common `rename_files` function in the `utils.dwi` module
- The function `extract_bids_identifier_from_caps_filename` is moved from `dwi_dti_utils` to `utils.dwi` since it is common to all DWI pipelines (could be made even more generic but let's do it gradually...). 
- It is renamed to `extract_bids_identifier_from_filename` because I don't see what is specific to CAPS structure in its logic.
- Type hints and documentation are added
- Unit tests for `rename_files` are added
> [REF] Refactor `rename_into_caps` DWI utilities

- clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_pipeline.py
- clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_utils.py
- clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_workflows.py
- clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_pipeline.py
- clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_workflows.py
- clinica/utils/dwi.py
- test/nonregression/pipelines/test_run_pipelines_dwi.py
The goal of this PR is to simplify the `DWIPreprocessingUsingPhaseDiff` workflow.
This workflow is already written as a sequence of steps separated by comments. Having these steps implemented in separate workflows would make things much easier to test and understand.
Furthermore, the pipeline relies on `Eddy` in various places but doesn't use the `eddy_fsl_pipeline` defined for the `DWIPreprocessingUsingT1` pipeline. 
This PR thus proposes to:
- extract the first step of the pipeline in its own workflow `compute_reference_b0`
- within this extracted workflow, use the `eddy_fsl_pipeline` instead of re-doing everything from scratch
- replace the third step by another call to `eddy_fsl_pipeline` for the same reasons
Note: To do that, I had to slightly modify the `eddy_fsl_pipeline` from the …
> [REF] Use `eddy_fsl_pipeline` in `DWIPreprocessingUsingPhasediff`

- clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_utils.py
- clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_workflows.py
- test/unittests/pipelines/dwi_preprocessing_using_t1/test_dwi_preprocessing_using_t1_utils.py
- refactor `change_itk_transform_type` to use more modern `pathlib` functionalities
- rename confusing `expend_matrix_list(in_matrix, in_bvec)` to `broadcast_matrix_filename_to_match_b_vector_length(matrix_filename: str, b_vectors_filename: str) -> list` and refactor
- rename `rotate_bvecs(in_bvec, in_matrix)` to `rotate_b_vectors(b_vectors_filename: str, matrix_filenames: list) -> str`
- Add type hints and documentation for the three functions
- Add unit tests for the three functions
> [REF TEST] refactor and add unit tests to DWI EPI pipeline utility functions

- clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_utils.py
- clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_workflows.py
- test/nonregression/pipelines/test_run_pipelines_dwi.py
This PR proposes to add a test for the workflow `prepare_phasediff_fmap`, which is part of the second step of the `DWIPreprocessingUsingPhasediff` pipeline.
It also:
- improves the related documentation
- improves the variable names and connection names
- enables the workflow to write to a custom location
The test is pretty fast and should run in less than a minute.
This requires the data I have generated here : https://github.com/aramis-lab/clinica_data_ci/pull/28
> [TEST] Test workflow `prepare_phasediff_fmap`

- clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_pipeline.py
- clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_workflows.py
- test/nonregression/pipelines/test_run_pipelines_dwi.py
Similar to #893 for Step 1, this PR proposes to extract the Step 2 of the `DWIPreprocessingUsingPhaseDiff` pipeline into its own workflow: `calibrate_and_register_fmap`
This PR also proposes to add functional tests for the extracted workflow in isolation. 
The added test is classified as "fast" as it is running in about 1 minute. It requires the data I have generated here: https://github.com/aramis-lab/clinica_data_ci/pull/29
> [REF] Extract Step 2 of `DWIPreprocessingUsingPhasediff` into its own workflow

- poetry.lock
- pyproject.toml
This PR proposes to add `pytest-mock` and `pytest-random-order` to the testing dependencies.
The former is used in #883 and #907 and I'd like to randomize the execution order of unit tests to avoid test pollution (to be done in another PR).
> [INFRA] add `pytest-mock` and `pytest-random-order` to dependencies

- clinica/pipelines/machine_learning_spatial_svm/spatial_svm_pipeline.py
- test/instantiation/test_instantiate_all_pipelines.py
- test/nonregression/pipelines/test_run_pipelines_ml.py
The command-line `machinelearning-prepare-spatial-svm` currently does not work, because the variable requested by the pipeline is `orig_input_data`, and the it is provided `orig_input_data_ml`
> Fix variables for spatial svm

- clinica/iotools/converters/oasis3_to_bids/oasis3_to_bids_cli.py
- clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py
- docs/Converters/OASIS3TOBIDS.md
This PR improves a few key points:
> Oasis3 improvements

- clinica/iotools/converter_utils.py
- test/unittests/iotools/test_converter_utils.py
Related to issue #913 and follow-up PR of #914 
This PR proposes some improvements to the function `viscode_to_session` such as to avoid cryptic errors due to invalid conversions to integer.
More precisely:
- Add the possibility to pass custom baseline identifiers which automatically return "ses-M000"
- Improve docs and add examples
- Use regex in order to make sure the conversion to integer will work
- If the input doesn't match the pattern, raise a meaningful error
- Add unit tests for the added functionalities
> [ENH] Improve function `viscode_to_session`

- clinica/iotools/converters/adni_to_bids/adni_utils.py
- test/unittests/iotools/converters/adni_to_bids/test_adni_utils.py
This PR proposes to:
- Make `get_preferred_visit_name` "private" (becomes `_get_preferred_visit_name`) since it is only used in this module.
- Refactor the code to make it easier to understand (the complex imbrication of `if/elif/else` wasn't easy to follow).
- Raise meaningful errors when unexpected values are received.
- Add unit tests.
There are a few weird things that I discovered when writing the unit tests prior to refactoring. I kept them for backward compatibility concerns but it might be worth taking a closer look....
> [REF, TEST] Add tests and refactor ADNI `get_preferred_visit_name`

- .gitignore
- clinica/pipelines/cli_param/option.py
- clinica/pipelines/pet_linear/pet_linear_cli.py
- clinica/pipelines/pet_linear/pet_linear_pipeline.py
- clinica/pipelines/t1_linear/anat_linear_pipeline.py
- clinica/pipelines/t1_linear/flair_linear_cli.py
- clinica/pipelines/t1_linear/t1_linear_cli.py
- docs/Pipelines/T1_Linear.md
Hello all :)
For a project using ANTs we would need to have a deterministic setup. This is the aim of this PR in which a value can be given for the random seed of ANTs, thus leading to the same result (using the same computer).
Before merging it would be worth testing if the results are the same on different computers as well. Also this could be checked in the CI.
Best,
> Add random seed for ANTs

- clinica/iotools/converters/genfi_to_bids/genfi_to_bids_utils.py
This PR aims at two things:
This work will need a data CI PR, since it adds new files (`scans.tsv`) to the architecture, and should therefore break current tests.
> [GENFI] TSV improvements

- clinica/iotools/converters/genfi_to_bids/genfi_to_bids_utils.py
Some T1 are not correctly converted. This is due to the fact that the conversion is based on the series description and that for a large amount of T1, it is wrongly described as a T2 (not the other way around, as far as we know). `dcm2niix` makes the same mistake as well.
Therefore, we if the `SeriesDescription` is T1 or T2, we check the `EchoTime` and `RepetitionTime` that characterise T1 or T2.
This PR will need a change in the data CI because of that.
> [GENFI] Handle T1 converted as T2

- clinica/utils/group.py
- clinica/utils/ux.py
- test/unittests/utils/test_group.py
- test/unittests/utils/test_ux.py
Small PR adding unit tests for utility functions in `clinica.utils.groups`.
Also add type hints and Numpydoc compliance.
I noticed that the `extract_group_ids` function simply lists the folder `caps_directory/groups` without any check, and can easily return things that are invalid group IDs (like file names if there are some within `caps_directory/groups`). 
This could be on purpose if the function assumes a validated CAPS folder (but should be clarified in the docstring I think). Otherwise, it could be useful to add a small safety check.
> [TEST] Add unit tests for groups utils

- clinica/pipelines/pet_linear/pet_linear_pipeline.py
- clinica/pipelines/pet_linear/pet_linear_utils.py
- test/unittests/pipelines/pet_linear/test_pet_linear_utils.py
The general idea of this PR is to improve the BIDS compliance of the `PETLinear` pipeline.
The current output looks like this:
```
caps
└── subjects
├── sub-01
│   ├── ses-M000
│   │   ├── pet_linear
│   │   │   ├── sub-01_ses-M000_trc-18FFDG_pet_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_suvr-pons_pet.nii.gz
│   │   │   └── sub-01_ses-M000_trc-18FFDG_pet_space-T1w_rigid.mat
```
Where the suffix `pet` appears after the tracer while it shouldn't.
This PR proposes to:
- Refactor the `PETLinear` utility function `rename_into_caps`
- Improve documentation and variable names
- Fix the issue described above (which came from the fact that the suffix wasn't stripped from the BIDS source file name used to get the source entities)
- Update the `PETLinear` pipeline accordingly
- Add unit tests …
> [ENH] Improve BIDS compatibility of `PetLinear` CAPS output

- clinica/pipelines/t1_linear/anat_linear_pipeline.py
- clinica/pipelines/t1_linear/anat_linear_utils.py
- test/unittests/pipelines/t1_linear/test_anat_linear_utils.py
Similar to #935 but for `T1Linear` and `FLAIRLinear`.
This is what we currently produce:
```
├── in
│   ├── bids
│   │   ├── dataset_description.json
│   │   └── sub-01
│   │       └── ses-M000
│   │           └── anat
│   │               └── sub-01_ses-M000_T1w.nii.gz
│   └── subjects.tsv
└── ref
└── caps
└── subjects
└── sub-01
└── ses-M000
└── t1_linear
├── sub-01_ses-M000_T1w_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_T1w.nii.gz
├── sub-01_ses-M000_T1w_space-MNI152NLin2009cSym_res-1x1x1_T1w.nii.gz
└── sub-01_ses-M000_T1w_space-MNI152NLin2009cSym_res-1x1x1_affine.mat
```
This PR requires the data PR https://github.com/aramis-lab/clinica_data_ci/pull/49
> [ENH] Improve BIDS compatibility of `T1Linear` and `FLAIRLinear` CAPS outputs

- clinica/utils/inputs.py
- test/unittests/utils/test_utils_inputs.py
This is a work-in-progress-PR to analyze how we could support run numbers in Clinica.
Some of our converters like GENFI2BIDS or OASIS32BIDS already output files with run numbers and pipelines have different behaviors in regard of this unsupported entity.
Most of the related logic lies around the `clinica_file_reader` function which relies on `_read_files_parallel` or `_read_files_sequential`. These two function take as input a BIDS/CAPS folder, a subject, a session, and a query, and they expect to get a single file based on these inputs.
If the input BIDS dataset contains some files with run numbers and if the query captures the different runs of a given acquisition, then the file reader will raise an error saying that too many files were found.
This PR investigates how we could allow the …
> [ENH] Enable the `clinica_file_reader` to work with run numbers

- clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_longitudinal_correction_utils.py
- clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_template_pipeline.py
- clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_template_utils.py
- clinica/utils/longitudinal.py
- test/unittests/utils/test_longitudinal.py
Small PR which proposes:
- to add unit tests to utility functions of `clinica.utils.longitudinal`.
- to add type hints and make docstrings Numpydoc compliant.
- to make some minor code refactoring.
> [TEST] Add unit test for longitudinal utils

- clinica/iotools/bids_utils.py
- clinica/iotools/converters/aibl_to_bids/aibl_utils.py
This PR proposes to remove the function `get_sessions_map_AIBL` which was in the wrong utility module (iotools bids utils instead of AIBL utils) and wasn't using some of its inputs.
Since it basically does a dictionary comprehension without providing much additional value, I think we can remove it completely.
> [MAINT] remove `get_sessions_map_AIBL`

- clinica/iotools/utils/data_handling.py
- test/unittests/iotools/utils/test_data_handling.py
Small refactoring of `compute_default_filename` in `data_handling.py`.
- rename and make function private
- use pathlib methods instead of string manipulations
- move folder creation logic within this function to simplify caller's code
- add small docstring
- add unit tests
> [REF TEST] Refactor `compute_default_filename`

- clinica/iotools/converters/adni_to_bids/adni_utils.py
- test/unittests/iotools/converters/adni_to_bids/test_adni_utils.py
Similarly to #924 and #926, this PR proposes some refactoring and unit test additions for a utility function (`get_closest_visit`) of the ADNI to BIDS converter.
> [REF, TEST] Add tests and refactor adni utility `get_closest_visit`

- poetry.lock
See [CVE-2023-37920](https://nvd.nist.gov/vuln/detail/CVE-2023-37920)
> [MAINT] Bump `certifi` to `2023.7.22`

- Makefile
- poetry.lock
Triggered by this recent warning message:
```shell
$ make install
poetry lock --check is deprecated, use `poetry check --lock` instead.
```
> MNT: Fix lock file checking

- clinica/iotools/converters/adni_to_bids/adni_utils.py
Related to #966
Simple PR proposing to add some logging when the filtering of clinical data results in an empty dataframe in ADNI2BIDS.
This will make it easier to understand potential ValueError you might get if all CSV files parsing results in empty dataframes.
> ADNI2BIDS: Log when dataframes extracted from clinical data are empty

- clinica/utils/check_dependency.py
- docs/Third-party.md
This PR proposes to remove the environment variables check for ANTS. 
Since ANTS `2.5.0` the variable ANTSPATH has been removed and checking for its existence will make users unable to use ANTS-based pipelines.
> Do not check for `ANTSPATH` anymore

- .jenkins/docs.Jenkinsfile
This PR fixes the issue of the outdated documentation we currently have.
The problem comes from the fact that the deployment step does not overwrite the remote if a folder already exists with the same name. This means that a documentation version is created for the first commit of each PR, creating a folder `PR-XXX` on the remote, but this folder is not updated afterwards. 
Way more problematic, the development version of the documentation, which is the default documentation that users browse when going to the online docs, currently shows an outdated version of the docs since it internally corresponds to a folder named "dev" which was created a while back, but is never overwritten.
This PR sets the `cleanRemote` option of the SSHPublisher to `True` with a change in the remote path to be …
> [INFRA] Fix outdated documentation

- .github/workflows/test_converters.yml
- .github/workflows/test_instantiation.yml
- .github/workflows/test_non_regression_fast.yml
Should speed Conda environment setup by re-using the previous Poetry cache if the project's lock file has not been modified.
This PR implements the following:
- Persistence of Poetry's cache using `actions/setup-python`
- Ensure Poetry uses the Conda environment instead of creating a new one
- Pin the version of Python and Poetry to avoid accidental upgrades
This is restricted to Linux *only*, since the macOS runner machines cannot use `actions/setup-python` as they are configured today.
> CI: Enable cache for Poetry

- clinica/pipelines/t1_linear/anat_linear_utils.py
Fix issue discovered in #998 with session labels in the output files of `T1Linear`.
Because of the behavior of the Python `rstrip()` string method, when stripping the suffix "T1w", the session labels ending with such characters "1", "T", or "w" are stripped from these...
Here is an example where the last "1" is removed in the output :
```
$ tree
.
├── bids
│   ├── sub-001
│   │   └── ses-01
│   │       └── anat
│   │           └── sub-001_ses-01_T1w.nii.gz
│   ├── sub-002
│   │   └── ses-01
│   │       └── anat
│   │           └── sub-002_ses-01_T1w.nii.gz
│   └── sub-003
│       └── ses-01
│           └── anat
│               └── sub-003_ses-01_T1w.nii.gz
├── caps
│   └── subjects
│       ├── sub-001
│       │   └── ses-01
│       │       └── t1_linear
│       │           ├── …
```
> [FIX] Fix bad session labels in `T1Linear` pipeline

- clinica/iotools/converters/genfi_to_bids/genfi_to_bids.py
Currently, the `Genfi2BIDS` converter parses the corresponding markdown file in the documentation to retrieve the project URL and description. This was implemented in order to avoid duplicating this information in the code.
This works great when installing Clinica from source since the `docs` folder is cloned as being part of the repository. However, when installing a released version (`pip install clinica`), only the source code (i.e. content of the `clinica` folder) is available in `site-packages`.
This causes the converter to break when trying to retrieve the link and description.
This PR proposes to go back to hardcoding these in order to fix the converter while a more elegant solution is found.
> [FIX] Hardcode link and description for `Genfi2BIDS`

- clinica/iotools/utils/cli.py
- clinica/iotools/utils/data_handling.py
- clinica/iotools/utils/pipeline_handling.py
> [FIX] Fix `merge-tsv` iotools

- .pre-commit-config.yaml
There seems to be an issue with the current pre-commit config, at least for some users.
This PR proposes to bump isort to 5.12.0 which solves the issue.
> [INFRA] Update `isort` version in `pre-commit` config

- .pre-commit-config.yaml
In case there is an inconsistency, then one would get:
```
poetry-check.............................................................Failed
- hook id: poetry-check
- exit code: 1
Error: poetry.lock is not consistent with pyproject.toml. Run `poetry lock [--no-update]` to fix it.
```
> MAINT: Add hook to ensure consistency of Poetry files

- clinica/utils/inputs.py
There was a problem with the function `_list_subjects_sub_folders` that prints the sentence 'Could not determine if {folder} is a CAPS or BIDS directory. Clinica will assume this is a CAPS directory.' every time it is called.
> Fix bad warning 

- clinica/utils/dwi.py
Closes #1034 
The current converters do not correct the PhaseEncodingDirection if it is not BIDS compliant leaving open the possibility of positive values (y+ instead of y for instance). This PR transforms these positive values so that the pipeline will not crash.
> Fix dwi positive direction in dwi-preprocessing

- .github/workflows/test_non_regression_fast.yml
- .github/workflows/test_pipelines_anat_freesurfer.yml
The anat non regression tests take a very long time to run.
This PR proposes to split them in two different tests workflows:
- one for freesurfer-based pipelines which will run every Tuesday at 8pm
- and one for the other pipelines (linear and volume) which will run every Thursday at 8pm
Note: for now I've copy-pasted some code, this should be mitigated once #989 is finished by using a bash script to run pytest commands.
> [INFRA] Split the anat pipelines between freesurfer-based and others

- clinica/iotools/utils/data_handling.py
- clinica/pipelines/engine.py
- clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_longitudinal_cli.py
- clinica/pipelines/t1_volume/t1_volume_cli.py
Fix small bug introduced in #1052 (`ss_file` argument was changed to `subject_session_file` for clarity but one call was forgotten).
This PR also proposes to make all calls to `get_subject_session_list` less ambiguous by either using the default values or specifying the name of the named arguments.
> [FIX] Fix calls to `get_subject_session_list`

- .github/workflows/test_converters.yml
- .github/workflows/test_non_regression_fast.yml
This PR proposes to:
- Clean working directories after test pipelines (seems to be causing some issues and we don't want tests to use cached results anyway).
- Run the fast non regression tests (which aren't so fast) on the dev branch instead of on pull requests. This should avoid jobs congestions on our self-hosted runners, especially when multiple PRs are updated at the same time.
> [CI] Run fast non regression tests on main

- .github/workflows/test_pipelines_anat.yml
This PR proposes to split the non regression tests for `t1-linear` and `t1-volume` in distinct jobs with distinct timeouts.
> [CI] Split `t1-linear` and `t1-volume` non regression tests

- clinica/pipelines/dwi_connectome/dwi_connectome_pipeline.py
- clinica/pipelines/dwi_dti/dwi_dti_pipeline.py
- clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_pipeline.py
- clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_pipeline.py
- clinica/pipelines/engine.py
- clinica/pipelines/machine_learning_spatial_svm/spatial_svm_pipeline.py
- clinica/pipelines/pet_linear/pet_linear_pipeline.py
- clinica/pipelines/pet_surface/pet_surface_pipeline.py
- clinica/pipelines/pet_volume/pet_volume_pipeline.py
- clinica/pipelines/statistics_surface/pipeline.py
- clinica/pipelines/statistics_volume/statistics_volume_pipeline.py
- clinica/pipelines/statistics_volume_correction/statistics_volume_correction_pipeline.py
- clinica/pipelines/t1_freesurfer/t1_freesurfer_pipeline.py
- clinica/pipelines/t1_freesurfer_atlas/t1_freeesurfer_atlas_pipeline.py
- clinica/pipelines/t1_freesurfer_longitudinal/longitudinal_utils.py
- clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_longitudinal_correction_pipeline.py
- clinica/pipelines/t1_freesurfer_longitudinal/t1_freesurfer_template_pipeline.py
- clinica/pipelines/t1_linear/anat_linear_pipeline.py
- clinica/pipelines/t1_volume_create_dartel/t1_volume_create_dartel_pipeline.py
- clinica/pipelines/t1_volume_dartel2mni/t1_volume_dartel2mni_pipeline.py
- clinica/pipelines/t1_volume_parcellation/t1_volume_parcellation_pipeline.py
- clinica/pipelines/t1_volume_register_dartel/t1_volume_register_dartel_pipeline.py
- clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py
- pyproject.toml
- test/unittests/pipelines/test_nipype_engine.py
This PR proposes to use Pathlib Path objects to represent paths in Pipeline classes instead of raw strings.
It does some refactoring of the pipeline engine first and propagate the changes to all Clinica pipelines.
This needs to be tested on the CI to check that pipelines were not broken.
> Use pathlib in pipelines

- .github/workflows/test_pipelines_dwi.yml
- .github/workflows/test_pipelines_dwi_preprocessing.yml
Following #1066 this PR is a portion of #989 and only adds two new workflows running on Github actions as cron jobs for DWI pipelines. 
- Testing of DWI preprocessing pipelines will happen every Monday at 8pm
- Testing of DWI pipelines will happen every Friday at 8pm
It relies on the test splitting done in #1066
> [CI] Run DWI non regression tests on GitHub actions

- clinica/pipelines/dwi_connectome/dwi_connectome_utils.py
- test/unittests/pipelines/dwi_connectome/test_dwi_connectome_utils.py
Follow-up PR to #1050 
Updates a utility function from DWIConnectome pipeline to handle new format for DWI files.
Also uses pathlib instead of os.path in other utility functions.
> [FIX] Update regexp dwi connectome utility function

- clinica/pipelines/dwi_dti/dwi_dti_cli.py
- clinica/pipelines/dwi_dti/dwi_dti_pipeline.py
- test/nonregression/pipelines/dwi/preprocessing/test_t1.py
- test/nonregression/pipelines/dwi/test_pipelines.py
This is a portion of #989 dealing with adding a random seed option to the CLI of the `DWIDTI` pipeline in order to set the random seed of the `RegistrationSynQuick` interface.
This PR also sets the random seed in related non regression tests.
> [ENH] Set the random seed in DWI pipeline using ANTs

- clinica/pipelines/dwi_preprocessing_using_fmap/utils.py
Fix bug introduced in #1072 
Function used as interfaces by Nippy need to be "self-contained".
The function `_get_output_file` needs to be imported explicitly even if defined in the same file as the calling functions.
> [FIX] Fix broken Nipype interfaces

- clinica/pipelines/dwi_preprocessing_using_fmap/pipeline.py
- clinica/pipelines/dwi_preprocessing_using_fmap/utils.py
- clinica/pipelines/dwi_preprocessing_using_fmap/workflows.py
- test/unittests/pipelines/dwi_preprocessing_using_fmap/test_dwi_preprocessing_using_fmap_utils.py
It looks like there is still an issue with the DWI preprocessing phasedidff pipeline after #1072 and #1073 
This should fix the incorrect file names. It also uses wrappers to define the Nipype tasks and adds some unit tests.
It also uses a working directory for these tasks in order to avoid writing to input BIDS folder or the current folder...
> [FIX] Fix bad names in DWI preprocessing using phasediff pipeline

- clinica/pipelines/dwi_preprocessing_using_fmap/pipeline.py
- clinica/pipelines/dwi_preprocessing_using_fmap/workflows.py
Fix for the DWI preprocessing using phase diff pipeline which was still using the `compute_average_b0` function instead of the wrapper `compute_average_b0_task`.
> [FIX] Use `compute_average_b0_task` in workflows

- .github/workflows/test.yml
- poetry.lock
- pyproject.toml
The main purpose of this PR is to add and test compatibility with Python 3.12. 
In the process, the following changes were also introduced:
- Drop Python 3.8
Rationales: It's difficult for Poetry to provide wheels for the latest versions of Python and macOS, whilst keeping compatibility with 3.8. NumPy, SciPy, Pandas et. are all dropping it, so we can't do much but follow their move.
- Drop some versioning constraints (nilearn, scikit-image, pytest-cov)
Rationales: Allow using the latest wheels for Linux and macOS.
⚠️ `nilearn` cannot be upgraded to version `0.10.x` due to `netneurotools`, see link to issues below.
- Update the locked dependencies
Rationales: To benefit from the latest wheels and accelerate CI.
- Move the test dependencies to the dev group
Rationales: `black`, `isort` et …
> [MAINT] Add compatibility with Python 3.12

- clinica/pipelines/statistics_surface/_utils.py
`np.object` is deprecated in favor of `np.object_`
Fixes one of the failures reported by the integration tests.
> BUG: Use appropriate numpy dtype for objects

- clinica/utils/inputs.py
Constructing a SSLContext object without setting a protocol explicitly triggers a deprecation warning since Python 3.10. This commits sets the protocol to `PROTOCOL_TLS_CLIENT` instead of `PROTOCOL_TLS`, since the latter is also deprecated.
> [BUG] Fix deprecation warning with SSL protocol

- clinica/pipelines/machine_learning/algorithm.py
Fix pep8 error introduced in #1090 which makes the linter fail on dev.
Wasn't captured by CI since the PR wasn't made from a fork.
> [FIX] Fix linter on dev

- .github/workflows/test_pipelines_anat.yml
Module Matlab 2017a is only available on Linux machines.
> [CI] Load module Matlab 2019b on MacOS CI machines

- docs/Pipelines/DWI_Connectome.md
- docs/Pipelines/DWI_DTI.md
- docs/Pipelines/DWI_Preprocessing.md
- docs/Pipelines/FLAIR_Linear.md
- docs/Pipelines/PET_Linear.md
- docs/Pipelines/PET_Surface.md
- docs/Pipelines/PET_Surface_Longitudinal.md
- docs/Pipelines/PET_Volume.md
- docs/Pipelines/Stats_Surface.md
- docs/Pipelines/Stats_Volume.md
- docs/Pipelines/T1_FreeSurfer.md
- docs/Pipelines/T1_FreeSurfer_Longitudinal.md
- docs/Pipelines/T1_Linear.md
- docs/Pipelines/T1_Volume.md
- docs/Third-party.md
Partly linked to #820, this PR proposes to improve the documentation for the installation of third party softwares.
Instead of having them simply listed in a bullet point list, this PR proposes to have a proper section for each software, with subsections concerning installation steps and configuration steps.
This also changes the explanations about environment variables which were all grouped in a single section.
This could be annoying to users who might only need a subset of them.
With the proposed organization, they only need to define the environment variables described in the configuration section of the software they are interested in.
Finally, this way of organizing things makes it possible to link directly to specific software from pipeline pages instead of linking the third-party …
> [DOC] Improve third-party software documentation page

- clinica/iotools/converters/adni_to_bids/adni_to_bids.py
- clinica/iotools/converters/aibl_to_bids/aibl_to_bids.py
- clinica/iotools/converters/genfi_to_bids/genfi_to_bids_cli.py
- clinica/iotools/converters/nifd_to_bids/nifd_to_bids_cli.py
- clinica/iotools/converters/oasis3_to_bids/oasis3_to_bids_cli.py
- clinica/iotools/converters/ukb_to_bids/ukb_to_bids_cli.py
- clinica/pipelines/dwi/connectome/utils.py
- clinica/pipelines/dwi/dti/pipeline.py
- clinica/pipelines/engine.py
- clinica/pipelines/statistics_surface/_utils.py
- clinica/pipelines/t1_freesurfer/t1_freesurfer_visualizer.py
- clinica/utils/atlas.py
- clinica/utils/check_dependency.py
- clinica/utils/exceptions.py
- clinica/utils/mri_registration.py
- clinica/utils/spm.py
- docs/Third-party.md
- test/nonregression/iotools/test_run_converters.py
- test/unittests/pipelines/dwi/test_connectome_utils.py
- test/unittests/utils/test_check_dependency.py
- test/unittests/utils/test_spm.py
Closes #820 
This PR proposes to refactor the checking logic for third party dependencies, especially around SPM which was handled in very complicated ways with lots of code duplication.
This PR also solves the weird environment variable configuration which was required to use SPM standalone.
That is, it removes the need to specify a value for `SPM_HOME`. Only `SPMSTANDALONE_HOME` and `MCR_HOME` should be defined and point to the right locations.
Finally, this PR adds a lot of unit tests to improve the robustness of these functions.
> [REF] Refactor dependency checking logic for third party softwares

- clinica/pipelines/dwi/preprocessing/t1/workflows.py
- clinica/pipelines/dwi/preprocessing/utils.py
- clinica/utils/filemanip.py
- test/nonregression/pipelines/dwi/preprocessing/test_phase_diff.py
- test/unittests/pipelines/dwi/preprocessing/test_common_preprocessing_utils.py
- test/unittests/utils/test_filemanip.py
This PR proposes to move a few functions specific to DWI preprocessing pipelines from the `clinica.utils.filemanip` module to the `clinica.pipelines.dwi.preprocessing.utils` module, in order to reduce coupling.
> [REF] Move DWI specific functions from `filemanip.py` utils to dwi preprocessing utils

- clinica/utils/inputs.py
- test/unittests/utils/test_utils_inputs.py
As per the BIDS specifications, the [dataset_description.json](https://bids-specification.readthedocs.io/en/stable/modality-agnostic-files.html#dataset_descriptionjson) file is mandatory.
This PR proposes the following:
- add a check for existence of a `dataset_description.json` file in the utility function `check_bids_folder()`.
- small refactoring of this function (each check is moved to a separate function).
- add a `DatasetType` enumeration instead of relying on "BIDS" and "CAPS" strings (might move it later to a better place in the code base...).
- add unit tests for the added check and refactor the test function for `check_bids_folder()` to have smaller and more readable tests.
Note: An unused function `_check_dataset_description_exists_in_caps()` has been added to prepare for #1101 …
> [ENH] Check that BIDS folders have a `dataset_description.json` file

- clinica/pipelines/dwi/preprocessing/t1/tasks.py
- clinica/pipelines/dwi/preprocessing/t1/workflows.py
- clinica/utils/image.py
This PR proposes to move the adapter function `merge_nifti_images_in_time_dimension_task` from `clinica.utils.image` to `clinica.pipelines.dwi.preprocessing.t1.tasks` where other tasks for this pipeline are defined.
The function definition is kept in the image module.
> [MAINT] Move `merge_nifti_images_in_time_dimension_task` in dwi tasks module

- clinica/pipelines/pet_linear/pet_linear_pipeline.py
- clinica/pipelines/pet_linear/pet_linear_utils.py
- clinica/pipelines/t1_linear/anat_linear_pipeline.py
- clinica/pipelines/t1_linear/anat_linear_utils.py
- clinica/pipelines/tasks.py
- clinica/pydra/pet_linear/tasks.py
- clinica/utils/image.py
> [ENH] Move crop_nifti function

- .github/workflows/test.yml
This PR replaces the macOS image target from `macos-latest` to `macos-12` for unit tests supposed to run on Intel chips.
This is because the former now refers to `macos-14` ARM which is not playing nice with our test suite with Python >= 3.11 atm...
I'll open a dedicated issue to remember to investigate why this is the case.
> [CI] Fix MacOS GitHub runner target

- clinica/pydra/tasks/__init__.py
- clinica/pydra/tasks/readers.py
- clinica/pydra/tasks/templates.py
Depends on https://github.com/nipype/pydra/issues/751
> [ENH] Add tasks for reading BIDS files and dataset

- clinica/cmdline.py
- clinica/iotools/converters/adni_to_bids/adni_utils.py
The function `create_file` in the adni-to-bids converter is executed in a multiprocessing context but doesn't handle the logging of messages in the sense that child processes do not configure their own logger.
This has a few consequences like the fact that messages logged from child processes aren't formatted or might even be missing.
This PR proposes a quick fix of re-configuring the clinica logger in child processes.
Ideally, we should have a process-safe logging architecture which would avoid race conditions (especially when logging to files for instance).
A classical solution is to dedicate a process to the logging task while other working processes send their logging messages through a Queue.
> [FIX] Fix logging in adni to bids

- clinica/cmdline.py
Fix a bug introduced in #1181 where handlers were added to the logger in an uncontrolled way.
Thanks for catching this @AliceJoubert !
> [FIX] Fix handlers addition to the clinica logger

- clinica/iotools/bids_utils.py
- clinica/iotools/converters/adni_to_bids/adni_modalities/adni_av45_fbb_pet.py
- clinica/iotools/converters/adni_to_bids/adni_modalities/adni_dwi.py
- clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fdg_pet.py
- clinica/iotools/converters/adni_to_bids/adni_modalities/adni_flair.py
- clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fmap.py
- clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fmri.py
- clinica/iotools/converters/adni_to_bids/adni_modalities/adni_pib_pet.py
- clinica/iotools/converters/adni_to_bids/adni_modalities/adni_t1.py
- clinica/iotools/converters/adni_to_bids/adni_modalities/adni_tau_pet.py
- clinica/iotools/converters/adni_to_bids/adni_to_bids.py
- clinica/iotools/converters/adni_to_bids/adni_utils.py
- test/unittests/iotools/converters/adni_to_bids/test_adni_utils.py
This PR adresses the behavior described in issue #398. 
- New functions were added in adni_utils.py to define the subjects list to convert, either from the given raw ADNI dataset or a subject list. Handles cases where there is no corresponding clinical data. 
- Unit tests were also added.
> [ENH] ADNI-to-BIDS converts only subjects in the provided ADNI directory if no subjects list is given

- .github/workflows/build_and_deploy.yml
Fix bug (discovered in #1199) in the deploy step of the documentation pipeline.
The folder containing the documentation artifact was deployed within the already deployed documentation instead of replacing it...
> [CI] Fix deploy step in documentation pipeline

- docs/Converters/ADNI2BIDS.md
Complete ADNI-to-BIDS documentation :
- Add description for FMAP process steps
- Add known problematic subjects/sessions
> [DOC] ADNI-to-BIDS : add Field Mapping (FMAP) specificities

- test/nonregression/iotools/test_run_converters.py
PR #1140 requires that testing data for converters have standardized input and output structures.
The `habs-to-bids` converter test uses data breaking this "standard" in two ways:
- The input data files are not in a folder named "unorganized"
- The output data files are not in a folder named "bids"
The data PR https://github.com/aramis-lab/clinica_data_ci/pull/64 restructures the test data and this PR updates the test to use the correct folders.
> [TEST] Update test for habs-to-bids converter

- test/nonregression/iotools/test_run_converters.py
PR #1140 requires that testing data for converters have standardized input and output structures.
The aibl-to-bids converter test uses data breaking this "standard" in two ways:
- The input clinical data files are not in a folder named "clinical_data" but in "Data_extract_3.2.5"
- The input data files are not in a folder named "unorganized" but in "unorganized_data"
The data PR  https://github.com/aramis-lab/clinica_data_ci/pull/66 restructures the test data and this PR updates the test to use the correct folders.
Related: PR #1202
> [TEST] Update test for aibl-to-bids converter

- clinica/iotools/bids_utils.py
- test/unittests/iotools/test_bids_utils.py
Create a unit test for the function `create_participants_df` from `bids_utils` to test before refactoring it. Parametrized only with datasets ADNI, OASIS1 and OASIS3 since the function is only used for ADNI and OASIS1.
> [MAINT] Missing unit tests for bids_utils

- clinica/pipelines/cli_param/argument.py
- clinica/pipelines/cli_param/option.py
- clinica/pipelines/pet_linear/pet_linear_utils.py
- clinica/pipelines/pet_surface/pet_surface_utils.py
- clinica/utils/input_files.py
- clinica/utils/pet.py
- docs/Pipelines/PET_Introduction.md
- docs/Pipelines/PET_Linear.md
- docs/Pipelines/PET_Volume.md
- docs/Pipelines/Stats_Volume.md
- test/instantiation/test_instantiate_all_pipelines.py
- test/nonregression/pipelines/pet/test_pet_linear.py
- test/nonregression/pipelines/pet/test_pet_surface.py
- test/nonregression/pipelines/pet/test_pet_volume.py
- test/nonregression/pipelines/test_run_pipelines_ml.py
- test/nonregression/pipelines/test_run_pipelines_stats.py
- test/unittests/pipelines/pet_linear/test_pet_linear_utils.py
- test/unittests/utils/test_pet.py
The SUVR reference region is modeled as a plain string in Clinica with a set of authorized values defined in a list:
https://github.com/aramis-lab/clinica/blob/42dcbd5fb1641011d2881eb9ce8d790b5a86c730/clinica/utils/pet.py#L138
This PR proposes to use a proper enumeration instead.
> [ENH] Use enumeration for SUVR reference regions

- clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py
Should fix the error `TypeError: EnumType.call() missing 1 required positional argument: 'value'` when using the ADNI-to-BIDS converter without any modality.
Recently introduced in #1140
> [FIX] Fix issue with enumeration as default value in CLI

- clinica/pipelines/anatomical/freesurfer/utils.py
- clinica/utils/image.py
- test/nonregression/pipelines/pet/test_pet_surface.py
- test/unittests/pipelines/anatomical/freesurfer/test_freesurfer_utils.py
Small PR proposing to add a proper enumeration for hemispheres instead of hardcoding "lh" and "rh" across the code base.
I haven't used it in `PETSurface` related code since I will directly use it in a future refactoring PR similar to the ones I did for `PETLinear` and `PETVolume`.
> [ENH] Add enumeration for hemispheres

- clinica/iotools/converters/adni_to_bids/adni_json.py
- clinica/utils/stream.py
Very small PR which proposes to add a `log_and_raise` function to `clinica.utils.stream` to automatically log (using `cprint`) and raise a given error message. This will be useful for example in #1237 
Also modifies `adni_json.py` where a less generic function was used to log and raise a specific error type.
> [ENH] Add function `log_and_raise`

- clinica/iotools/utils/data_handling.py
- clinica/iotools/utils/pipeline_handling.py
- test/unittests/iotools/utils/test_pipeline_handling.py
This PR fixes a couple bugs on the iotools `merge-tsv` which occurs when providing a CAPS folder for `T1Freesurfer`.
These bugs were introduced in #869 (from clinica `0.7.4`).
- The parameter `group_selection` was not properly handled
- The `T1Freesurfer` pipeline has no groups in its CAPS and the metric extraction logic is thus a bit different. More precisely, the segmentation volume metrics were not extracted correctly.
This PR proposes to add some basic fixes as well as some unit tests.
> [FIX] Fix t1-freesurfer pipeline handler

- clinica/pipelines/engine.py
- clinica/utils/stream.py
Similar to #1238 but for warnings.
> [ENH] Add function `log_and_warn`

- clinica/utils/spm.py
- test/unittests/pipelines/statistics_volume/test_statistics_volume_utils.py
- test/unittests/utils/test_spm.py
Related to discussion #1256 
I believe this should avoid the "SPM not in matlab path" issue when using Matlab and SPM12.
> [FIX] Specify path to SPM when using Matlab and SPM12

- clinica/utils/input_files.py
- clinica/utils/spm.py
- test/unittests/utils/test_spm.py
Small PR to improve the way SPM index tissues are represented and the way they are mapped to spm indices.
Instead of having a mutable mapping between integers and strings, this PR proposes to have an enumeration for the SPM tissues and a simple function doing the mapping from integer indices to the right variant. This function raises a proper `ValueError` if the index doesn't correspond to a tissue.
The PR also adds some basic unit tests.
> [ENH] Replace spm index tissue map mapping with enum

- clinica/utils/stream.py
- test/unittests/utils/test_stream.py
The enumeration `LoggingLevel` is currently implemented as an `StrEnum` which does not reflect the ordering of the different levels. For example, we expect to be able to do things like:
```python
level = LoggingLevel.INFO
if level < LoggingLevel.ERROR:
```
This PR proposes to implement `LoggingLevel` as an `IntEnum`. It also adds some unit tests for the functions of the `clinica.utils.stream` module.
> [ENH] Implement `LoggingLevel` as an `IntEnum`

- docs/Converters/HABS2BIDS.md
All converters have been normalized to "XXX-to-bids" but this one managed its way through...
> [DOC] Modify `habs-to-bids` name in documentation title

- clinica/utils/check_dependency.py
- test/unittests/utils/test_check_dependency.py
This PR proposes to add utilities to retrieve the version numbers of the third-party softwares that Clinica depends on.
There are three main functions that have been added or modified in the public API of the `clinica.utils.check_dependency` module:
Returns the minimum version of a third party software that Clinica requires on a global level.
**Note:** It will be possible to overwrite this on a pipeline-by-pipeline basis through the use of the `info.json` configuration file. 
Here is an example:
```python
>>> from clinica.utils.check_dependency import get_software_min_version_supported
>>> get_software_min_version_supported("ants")
<Version('2.5.0')>
>>> get_software_min_version_supported("spm")
<Version('12.7219')>
```
Returns the installed version of a third party software. This …
> [ENH] Add third-party software version getters

- clinica/utils/stream.py
Fix bug introduced recently in #1267 
When the logging level is passed as a string or an integer to `cprint`, it needs to be converted to the corresponding `LoggingLevel`.
The call to `get_logging_level` was just missing and all calls to `cprint` with a string or integer level were ignored.
> [FIX] Handle string and integer logging levels in `cprint`

- test/nonregression/pipelines/test_run_pipelines_stats.py
Related to #1269 
This PR proposes to skip the currently broken non regression test for the statistics-surface pipeline while we decide which way to go with `brainstat` and our implementation of this pipeline.
> [TEST] Skip statistic-surface test

- test/nonregression/iotools/test_run_converters.py
PR #1239 added a new converter named `ixi-to-bids` and added its name to the enumeration of converter names.
Because of this, there is currently a non regression test failing for this converter. It fails for a good reason though: we haven't built the test dataset yet so there is no data in the location expected by the test.
This PR proposes to temporarily skip the test for `ixi-to-bids` while #1273 is finished. It will avoid having the converter test suite marked with the nasty red cross of failure.
> [TEST] Temporarily skip non regression test for `ixi-to-bids`

- clinica/iotools/bids_dataset_description.py
- clinica/iotools/utils/cli.py
- clinica/iotools/utils/describe.py
- docs/IO.md
- mkdocs.yml
- poetry.lock
- pyproject.toml
- test/unittests/iotools/utils/test_describe.py
This PR proposes to add the command:
```bash
clinica iotools describe DATASET_PATH
```
which will basically parse the `dataset_description.json` file describing the dataset provided in order to display the information in a nice user-friendly way.
Here is a toy example with a BIDS and CAPS dataset having only their respective `dataset_description.json` file:
```bash
tree
.
├── bids
│   └── dataset_description.json
├── caps
│   └── dataset_description.json
```
We can describe them with the added tool:
> [ENH] Add `clinica iotools describe`

- .github/workflows/test_converters.yml
- .github/workflows/test_instantiation.yml
- .github/workflows/test_non_regression_fast.yml
- .github/workflows/test_pipelines_anat.yml
- .github/workflows/test_pipelines_anat_freesurfer.yml
- .github/workflows/test_pipelines_dwi.yml
- .github/workflows/test_pipelines_dwi_preprocessing.yml
- .github/workflows/test_pipelines_pet.yml
- environment.yml
- Remove the auto-installation of Poetry in the pipelines (maintainers install and upgrade poetry directly on the VMs when needed)
- Bump poetry from 1.6.1 to 1.8.3
- Clean all virtual environments to start afresh
- Bump the Python version in the `environment.yml` from 3.10 to 3.11
> [CI] Clean CI workflows

- docs/CHANGELOG.md
- pyproject.toml
Prepare release `0.9.0` of Clinica.
> Release `0.9.0`

- poetry.lock
- pyproject.toml
Trying to fix our current install issues with release 0.9.0...
> [FIX] Bump `scipy` and make `brainstat` optional

- clinica/pipelines/anatomical/freesurfer/atlas/pipeline.py
- clinica/pipelines/anatomical/freesurfer/longitudinal/correction/pipeline.py
- clinica/pipelines/anatomical/freesurfer/longitudinal/template/pipeline.py
- clinica/pipelines/anatomical/freesurfer/t1/pipeline.py
- clinica/pipelines/dwi/preprocessing/fmap/pipeline.py
- clinica/pipelines/dwi/preprocessing/t1/pipeline.py
- clinica/pipelines/machine_learning_spatial_svm/spatial_svm_pipeline.py
- clinica/pipelines/pet/linear/pipeline.py
- clinica/pipelines/pet/volume/pipeline.py
- clinica/pipelines/pet_surface/pet_surface_pipeline.py
- clinica/pipelines/statistics_surface/pipeline.py
- clinica/pipelines/statistics_volume/statistics_volume_pipeline.py
- clinica/pipelines/t1_linear/anat_linear_pipeline.py
- clinica/pipelines/t1_volume_create_dartel/t1_volume_create_dartel_pipeline.py
- clinica/pipelines/t1_volume_dartel2mni/t1_volume_dartel2mni_pipeline.py
- clinica/pipelines/t1_volume_parcellation/t1_volume_parcellation_pipeline.py
- clinica/pipelines/t1_volume_register_dartel/t1_volume_register_dartel_pipeline.py
- clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py
- clinica/utils/inputs.py
- test/unittests/utils/test_utils_inputs.py
TO DISCUSS :  **change of a logic** for ```clinica_file_reader``` but also ```clinica_list_of_files_reader``` (DWI pipelines)
Currently ```clinica_file_reader``` returns a list of files and a list errors _messages/strings_. As such, complicated to retrieve what sub/ses is problematic + most of the time these are not used since function called like so ```files, _ = clinica_file_reader(...)```. Otherwise, used to stop the processing when a subject/session is missing files for ex. : a bit critical.
-> list of messages replaced by list of tuples with the actual problematic sessions
-> no more breaking when subject/session does not have files, they are removed from the lists of sub/sess
-> raise replaced by cprint. User informed that some files won't be processed instead so removed …
> [ENH]  Allow the T1-Linear pipeline to go over (subject, session) couples that do not have data

- clinica/iotools/converters/ixi_to_bids/ixi_to_bids_utils.py
> [FIX] IXI-to-BIDS function `define_participants` should output sorted participants list

- clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py
- clinica/iotools/converters/oasis_to_bids/oasis_to_bids_utils.py
- test/unittests/iotools/converters/oasis_to_bids/test_oasis_to_bids_utils.py
> [REF] OASIS-to-BIDS : improve code quality for function `create_sessions_dict`

- clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py
- clinica/iotools/converters/oasis_to_bids/oasis_to_bids_utils.py
- test/unittests/iotools/converters/oasis_to_bids/test_oasis_to_bids_utils.py
Partly adresses #1326, by adding a function to write tsv scans files specific to OASIS.
> [REF] OASIS-to-BIDS create_scans_dict

- clinica/pipelines/pet/linear/pipeline.py
> [FIX] Correct the `pet-linear` pipeline

- clinica/iotools/bids_utils.py
- test/unittests/iotools/test_bids_utils.py
> [FIX] ADNI-to-BIDS : incorporate the fix for KeyError "APGEN"

- clinica/iotools/converters/aibl_to_bids/utils/clinical.py
- test/unittests/iotools/converters/aibl_to_bids/test_aibl_utils.py
Close #1349 
!!! Function modifications for `_compute_ages_at_each_exam` and `_compute_exam_date_from_baseline`
> [TEST] AIBL-to-BIDS : add unit tests to functions related to creating sessions.tsv files

- clinica/pipelines/pet/linear/pipeline.py
This reverts commit 1fad1c3a3ccbd56b9b4c5f3fc1884ec602be4e55.
> Revert "[FIX] Correct the `pet-linear` pipeline (#1348)"

- clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py
- clinica/iotools/converters/oasis_to_bids/oasis_to_bids_utils.py
- test/unittests/iotools/converters/oasis_to_bids/test_oasis_to_bids_utils.py
> [REF] OASIS-to-BIDS writing sessions tsv files now use simpler code with data frames

- clinica/iotools/converters/aibl_to_bids/utils/clinical.py
- clinica/iotools/converters/specifications/sessions.tsv
- test/unittests/iotools/converters/aibl_to_bids/test_aibl_utils.py
> [REF] AIBL-to-BIDS : code refactoring for sessions file creation

- .pre-commit-config.yaml
- clinica/pipelines/dwi/preprocessing/t1/workflows.py
- clinica/pipelines/machine_learning_spatial_svm/spatial_svm_utils.py
Is there a CI run to run codespell or pre-commit?
> Progress codespell forward, fixup typos it detects

- docs/Software/Third-party.md
Following users issues and some tests, it seems the version of dcm2niix can cause trouble when converting some images. We should recommend a more recent version of dcm2niix in our documentation. WDYT @NicolasGensollen ?
> [FIX] Update the version of dcm2niix required to run clinica converters

- clinica/iotools/bids_utils.py
> [FIX] Fix type mismatch in `clinica.iotools.bids_utils`

- clinica/pipelines/pet/linear/pipeline.py
- clinica/pipelines/pet/linear/tasks.py
- clinica/pipelines/pet/linear/utils.py
- clinica/utils/image.py
- clinica/utils/testing_utils.py
- test/unittests/pipelines/pet/test_pet_linear_utils.py
- test/unittests/utils/test_image.py
Follow-up PR of #1355 
This PR proposes to:
- Add a new `clip_nifti` function to `clinica.utils.image` for generic clipping of nifty images
- Refactor `clip_img` to use `clip_nifti` with the computed threshold
- Provide the pipeline base directory as the `output_dir` of the clipping task such that clipped images aren't written in the current folder.
- Add unit tests for function `clip_nifti` and `clip_img`
> [REF] Refactor function `clip_img`

- docs/Pipelines/PET_Linear.md
> [DOC] Document clipping of background for `PetLinear`

- docs/glossary.md
Adding term fMRI to documentation glossary.md
Closes #1382
> add fMRI to documentation glossary

- clinica/pipelines/pet/linear/pipeline.py
- test/nonregression/pipelines/pet/test_pet_linear.py
Closes #1401 
Requires data PR https://github.com/aramis-lab/clinica_data_ci/pull/79 for the non regression tests to pass with the added option.
> [FIX] Fix pet-linear with option `--save_pet_in_t1w_space`

- clinica/pipelines/anatomical/freesurfer/longitudinal/correction/pipeline.py
- clinica/pipelines/engine.py
- clinica/pipelines/pet/linear/pipeline.py
- clinica/pipelines/t1_linear/anat_linear_pipeline.py
- clinica/utils/bids.py
- clinica/utils/filemanip.py
- clinica/utils/input_files.py
- clinica/utils/testing_utils.py
- test/unittests/pipelines/anatomical/freesurfer/atlas/test_t1_freesurfer_atlas_pipeline.py
- test/unittests/pipelines/anatomical/freesurfer/longitudinal/correction/test_t1_freesurfer_longitudinal_correction_pipeline.py
- test/unittests/pipelines/anatomical/freesurfer/longitudinal/template/test_t1_freesurfer_longitudinal_template_pipeline.py
- test/unittests/pipelines/dwi/connectome/test_dwi_connectome_pipeline.py
- test/unittests/pipelines/dwi/dti/test_dwi_dti_pipeline.py
- test/unittests/pipelines/dwi/preprocessing/test_dwi_preprocessing_using_fmap_pipeline.py
- test/unittests/pipelines/dwi/preprocessing/test_dwi_preprocessing_using_t1_pipeline.py
- test/unittests/pipelines/pet/test_pet_linear_pipeline.py
- test/unittests/pipelines/t1_linear/test_anat_linear_pipeline.py
- test/unittests/pipelines/t1_volume_create_dartel/test_t1_volume_create_dartel_pipeline.py
- test/unittests/pipelines/t1_volume_dartel2mni/test_t1_volume_dartel2mni_pipeline.py
- test/unittests/pipelines/t1_volume_parcellation/test_t1_volume_parcellation_pipeline.py
- test/unittests/pipelines/t1_volume_register_dartel/test_t1_volume_register_dartel_pipeline.py
- test/unittests/pipelines/t1_volume_tissue_segmentation/test_t1_volume_tissue_segmentation_pipeline.py
- test/unittests/pydra/test_interfaces.py
- test/unittests/utils/test_input_files.py
- test/unittests/utils/test_utils_inputs.py
Closes #1079 
This PR proposes to improve how pipelines determine which subject-session to skip. 
The base idea is to analyze the provided CAPS folder before running the processing pipeline and look for the expected output files. If those files are present for a given subject-session, then it won't be processed by the pipeline. This can save quite some time when re-running a pipeline.
This idea is definitely not new and some pipelines are already doing that (`T1Linear` and some Freesurfer longitudinal pipelines). Concretely, this is done in this method where the files are searched in the CAPS output folder:
https://github.com/aramis-lab/clinica/blob/7436f440a335794ffd1315c0936b797e7b11bca8/clinica/pipelines/t1_linear/anat_linear_pipeline.py#L71-L87
The initial feature request of #1079 was …
> [ENH] Skip visits for which processed images exist

- clinica/iotools/utils/center_nifti.py
- clinica/iotools/utils/cli.py
- clinica/iotools/utils/data_handling/_centering.py
- docs/IO.md
- test/unittests/iotools/utils/test_center_nifti.py
Adresses part of #1413
The modalities to center were set as described in the documentation. By default, `center_nifti` will only process T1w images. It is possible to change this by using the `--modality` option and you can process several modalities at the same time. 
Modalities are not restricted to a set of known modalities on our side to give the user more freedom. That means the user could enter `-m TOTO` if they wanted to, however the implementation is at the moment not very robust. **This can be changed.**
For follow-up PR : 
- Review the CI data et non regression tests to handle more cases (command line tested?)
- Review logic to check for files since split in 2 functions. Might be more practical to move the logic for it to be tested and completed (issue if output folder does not …
> [FIX] `Center_Nifti` should run by default on T1

- .github/workflows/test_converters.yml
- .github/workflows/test_instantiation.yml
- .github/workflows/test_non_regression_fast.yml
- .github/workflows/test_pipelines_anat.yml
- .github/workflows/test_pipelines_anat_freesurfer.yml
- .github/workflows/test_pipelines_dwi.yml
- .github/workflows/test_pipelines_dwi_preprocessing.yml
- .github/workflows/test_pipelines_pet.yml
Since the MacOS self-hosted runner is not working properly as a service, let's comment the related pipelines and avoid the consistently broken CI.
> [CI] Stop the macOS pipelines

- clinica/utils/exceptions.py
- clinica/utils/image.py
- test/unittests/utils/test_image.py
> [FIX] Fix function `crop_nifti` when bounding box is outside of the image

- clinica/pipelines/pet/linear/pipeline.py
- clinica/pipelines/t1_linear/anat_linear_pipeline.py
- clinica/pipelines/tasks.py
- clinica/utils/image.py
- test/unittests/utils/test_image.py
Following #1426, this PR proposes to improve the `crop_nifti` function.
Currently the function behaves in a very specific way, by cropping the provided image with a hardcoded bounding box that we defined for a specific use case (T1 images with MNI reference template). Therefore, I think the name is misleading and we could make use of a more generic function.
This PR proposes to make `crop_nifti` more generic by letting users provide both the bounding box and the reference image. If no bounding box is provided, then no cropping is performed. If no reference image is provided, the input image is used as a reference. In other words `crop_nifti(img)` with no other argument is the identity function.
The old `crop_nifti` has been renamed `crop_nifti_using_t1_mni_template` and is nothing more …
> [ENH] Improve the `crop_nifti`

- clinica/utils/participant.py
- clinica/utils/ux.py
- test/unittests/utils/test_ux.py
The function `print_images_to_process`:
https://github.com/aramis-lab/clinica/blob/d505ac2f23119856844fef9b285cf47e774ceb94/clinica/utils/ux.py#L11-L35
is used in various pipelines but was not tested in isolation.
This PR proposes:
- to add these unit tests
- simpler implementation relying on the builtin `defaultdict` instead of `get_unique_subjects`
- to give more possibilities for customization (logging level and maximum number of lines)
> [TEST] Refactor and test function `print_images_to_process`

- clinica/iotools/utils/center_nifti.py
- clinica/iotools/utils/cli.py
- clinica/iotools/utils/data_handling/_centering.py
- docs/IOTools/center_nifti.md
- test/unittests/iotools/utils/test_center_nifti.py
Closes #1413 following #1418 
Changes the option of `--center_all_files` to `--threshold` above which images are to be centered.
In other PR : 
- Add non regression tests that checks inside images and txt file
- Change CI data if necessary (might be interesting to have different thresholds/modalities to test)
- Use the new NiftiImage class in `_get_world_coordinate_of_center`
> [ENH] In `center-nifti`, give the option to the user to choose the centering threshold

- test/nonregression/iotools/test_run_utils.py
Following #1433, non-regression needed to be updated and completed with nifti comparison.
In the non-regression tests we are testing `center_all_nifti` and not `center-nifti`.  Is there a reason for this ? We are missing the txt file which can be quite useful.
> [TEST] Modify non-regression tests for `center-nifti`

- test/nonregression/pipelines/anat/test_t1_linear.py
- test/nonregression/testing_tools.py
- test/unittests/test_testing_tools.py
- Uses function `compare_niftis` in the FLAIR linear pipeline.
- `compare_niftis` was made a little more flexible by giving access to the metric threshold used as a requirement for similarity validation
We have images that don't pass the test right now. This might be partly due to the recent changes in the cropping function but some uncropped images tests aren't validated either. The threshold for the similarity metric is 0.9, I don't know if it makes sense to go lower or if we would need to update all the faulty images.
> [TEST] Add nifti comparison to FLAIR linear pipeline

- clinica/iotools/utils/center_nifti.py
- test/nonregression/iotools/test_run_utils.py
- test/nonregression/testing_tools.py
- test/unittests/iotools/utils/test_center_nifti.py
- test/unittests/test_testing_tools.py
#1438 follow-up
- Change from center_all_niftis to center_nifti
- Add non regression tests on the txt file
As of now breaks the CI because the txt file was not added to the CI ref folder. I would need to update the CI with it if this PR is validated. The test that is done on the file structure should stay as is though (i.e. not taking into account the txt file) since there is a timestamp in the txt file name.
> [TEST] Change function tested in non-regression for center-nifti

- test/nonregression/pipelines/anat/test_t1_linear.py
Closes #1444
Sets the random_seed parameter to 1 in Flair Linear tests.
> [FIX] Set a random_seed in Flair Linear non regression tests to produce deterministic results

- clinica/converters/ixi_to_bids/_utils.py
- test/nonregression/test_run_converters.py
Extends non regression tests to metadata files as part of #1450. The function writing sessions needed a little fixing.
> [TEST][FIX] IXI-to-BIDS : Add non-regression tests for metadata files

- clinica/utils/input_files.py
- test/unittests/utils/test_input_files.py
> [FIX] Change querying pattern in `bids_pet_nii` when `tracer` exists but `reconstruction` is None

- clinica/converters/_utils.py
- clinica/converters/ixi_to_bids/_utils.py
- clinica/converters/oasis_to_bids/_converter.py
- clinica/converters/oasis_to_bids/_utils.py
- clinica/converters/oasis_to_bids/cli.py
- test/nonregression/test_run_converters.py
- test/unittests/converters/test_converter_utils.py
- test/unittests/converters/test_ixi_to_bids_utils.py
- test/unittests/converters/test_oasis_to_bids_utils.py
> [CI] OASIS-to-BIDS : Add option --subjects-list and its functionality for oasis-to-bids converter

- clinica/converters/ukb_to_bids/_utils.py
- test/unittests/converters/test_ukb_to_bids_utils.py
While working on UKB-to-BIDS to extend #1450, I dug into the code for `sessions.tsv` writing and noticed a function that could be both improved and tested : 
https://github.com/aramis-lab/clinica/blob/c9ab28bec76c10ba8f8866555b39d713f640ce5a/clinica/converters/ukb_to_bids/_utils.py#L415-L453
The way of testing for nans was modified since it was doing nothing as it was.
> [REF][TEST] Refactor and test `_select_sessions` in UKB-to-BIDS utils

- .github/workflows/test_pipelines_anat.yml
Revert modification of cron for anat testing workflows made in #1486 and use manual dispatch instead.
> [CI] Allow manual execution of anat test workflow

- clinica/iotools/cli.py
- clinica/iotools/data_handling/_missing.py
- test/unittests/iotools/test_iotools_cli.py
Closes #1484 
This PR also proposes to add some unit tests related to the CLI client in order to avoid these kind of bugs (see issue #1485). The proposed solution consists of mocking the internal function and calling the CLI in the test with `CliRunner`. The tests then check the exit code as well as whether the mock was called and the arguments passed to it. Assuming the internal function is tested separately as well, this should be enough I believe. This testing strategy can be used for other CLI in order to close fully #1485.
> [FIX] Fix broken imports in CLI

- clinica/pipelines/pet_surface/pet_surface_utils.py
After creation of `pipelines.pet` module some functions were moved to `pet.utils` from `utils.pet` but imports were not changed for `pet-surface`. This pipeline is also expected to be in this module (cf #1237) but in the meantime these imports should be fixed.
> [FIX] Fix imports in `pet-surface`

- clinica/pydra/pet_volume/pipeline.py
Following PR #1497 there were some left-over imports that imported get_suvr_mask from `utils.pet`.
Adding the PR as these imports should be fixed while the pipeline is included in the new module (cf #1237).
> [FIX] Fix imports in  `pet-volume` after creation of pipelines.pet

- clinica/converters/genfi_to_bids/_converter.py
- clinica/converters/genfi_to_bids/_utils.py
Closes #1504
I will do the modification of the CI right after this one is merged and I rebased my branch for my other PR #1484. The nonregression tests should fail only because the scans files are now named `scans` and not `scan` in the CI reference.
> [FIX] Genfi-to-BIDS : modification of the source path of the image in scans tsv files

- clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_pipeline.py
- clinica/utils/testing_utils.py
- test/unittests/pipelines/t1_volume_tissue_segmentation/test_t1_volume_tissue_segmentation_pipeline.py
> [ENH] Skip processed visits for t1-volume-tissue-segmentation

- clinica/converters/genfi_to_bids/_utils.py
Closes #1509
Dicom dataframe was filtered, starting by dropping duplicates on one column. If the dataframe was not previously ordered on an adjacent column there was a possibility to not get the same output each time. This caused failing non-regression tests when comparing scans.tsv files. 
Current non-regression tests for GENFI can be expected to fail with this PR but should not when #1468 is rebased
> [FIX] GENFI : sort dicoms before dropping duplicates

- clinica/converters/ukb_to_bids/_utils.py
- test/nonregression/test_run_converters.py
- test/unittests/converters/test_ukb_to_bids_utils.py
Following the work in #1450.
In order to facilitate new regression tests on metadata, this PR :
> [REF] UKB : Modify tsv writing to fit BIDS specifications

- clinica/pipelines/pet/volume/pipeline.py
Closes #1528
Non-regression tests for the `pet-volume` pipeline should be checked also. They don't happen upon PR opening but weekly (see our Actions).
> [FIX] Pet-volume : modify `iterfields` to allow pipeline completion
